// <auto-generated>
//     Generated by eng/CatalogGen from the DiagnosticDescriptor instances declared by
//     Microsoft.CodeAnalysis.PublicApiAnalyzers 5.6.0 (language: cs).
//     Do not edit by hand: rerun the generator.
//
//     Only Id, Category, Title and HelpLinkUri are emitted, and only when the
//     descriptor actually supplies them. A rule's title is reproduced verbatim as its
//     documentation comment: it is the one sentence that says what the rule is about,
//     and it is Microsoft.CodeAnalysis.PublicApiAnalyzers's own wording. Rule descriptions and message
//     formats are the vendor's documentation and are not redistributed here.
// </auto-generated>

using DiagnosticCatalog;

[assembly: CatalogSource(
    source:        "Microsoft.CodeAnalysis.PublicApiAnalyzers",
    sourceVersion: "5.6.0",
    generatedOn:   "2026-08-05")]

namespace DiagnosticCatalog.PublicApi;

/// <summary>
/// The diagnostic categories used by Microsoft.CodeAnalysis.PublicApiAnalyzers, declared once each.
/// </summary>
/// <remarks>
/// INTERNAL by design. A category is reachable only through the rule that carries it:
/// write <c>SomeRule.Sxxxx.Category</c>, never the category constant directly. The two
/// spellings fold to the same string today and stop agreeing the day the vendor moves the
/// rule to another category -- the rule member follows, a category named on its own does
/// not, and the suppression is left asserting a category the rule no longer carries.
/// Nothing reports that: Roslyn ignores the category when it matches a suppression, so the
/// mistake has no symptom at all. Keeping this class out of the public surface makes that
/// decoupling unwritable rather than merely discouraged.
/// The public <c>Category</c> constant on each rule is initialised from here and folds to
/// the literal at compile time, so a consumer loses nothing.
/// </remarks>
[DiagnosticCategory]
internal static class PublicApiCategory
{
    /// <summary>The <c>ApiDesign</c> category.</summary>
    public const string ApiDesign = "ApiDesign";
}

/// <summary>
/// The Microsoft.CodeAnalysis.PublicApiAnalyzers diagnostic rules, as declared by that package's analyzers.
/// </summary>
public static class PublicApiRule
{
    /// <summary>Add public types and members to the declared API.</summary>
    /// <remarks>See <see href="https://github.com/dotnet/roslyn/blob/main/src/RoslynAnalyzers/PublicApiAnalyzers/PublicApiAnalyzers.Help.md"/>.</remarks>
    [DiagnosticRule]
    public static class RS0016
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(RS0016);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = PublicApiCategory.ApiDesign;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/dotnet/roslyn/blob/main/src/RoslynAnalyzers/PublicApiAnalyzers/PublicApiAnalyzers.Help.md";
    }

    /// <summary>Remove deleted types and members from the declared API.</summary>
    /// <remarks>See <see href="https://github.com/dotnet/roslyn/blob/main/src/RoslynAnalyzers/PublicApiAnalyzers/PublicApiAnalyzers.Help.md"/>.</remarks>
    [DiagnosticRule]
    public static class RS0017
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(RS0017);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = PublicApiCategory.ApiDesign;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/dotnet/roslyn/blob/main/src/RoslynAnalyzers/PublicApiAnalyzers/PublicApiAnalyzers.Help.md";
    }

    /// <summary>Constructor make noninheritable base class inheritable.</summary>
    /// <remarks>See <see href="https://github.com/dotnet/roslyn/blob/main/src/RoslynAnalyzers/PublicApiAnalyzers/PublicApiAnalyzers.Help.md"/>.</remarks>
    [DiagnosticRule]
    public static class RS0022
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(RS0022);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = PublicApiCategory.ApiDesign;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/dotnet/roslyn/blob/main/src/RoslynAnalyzers/PublicApiAnalyzers/PublicApiAnalyzers.Help.md";
    }

    /// <summary>The contents of the public API files are invalid.</summary>
    /// <remarks>See <see href="https://github.com/dotnet/roslyn/blob/main/src/RoslynAnalyzers/PublicApiAnalyzers/PublicApiAnalyzers.Help.md"/>.</remarks>
    [DiagnosticRule]
    public static class RS0024
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(RS0024);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = PublicApiCategory.ApiDesign;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/dotnet/roslyn/blob/main/src/RoslynAnalyzers/PublicApiAnalyzers/PublicApiAnalyzers.Help.md";
    }

    /// <summary>Do not duplicate symbols in public API files.</summary>
    /// <remarks>See <see href="https://github.com/dotnet/roslyn/blob/main/src/RoslynAnalyzers/PublicApiAnalyzers/PublicApiAnalyzers.Help.md"/>.</remarks>
    [DiagnosticRule]
    public static class RS0025
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(RS0025);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = PublicApiCategory.ApiDesign;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/dotnet/roslyn/blob/main/src/RoslynAnalyzers/PublicApiAnalyzers/PublicApiAnalyzers.Help.md";
    }

    /// <summary>Do not add multiple public overloads with optional parameters.</summary>
    /// <remarks>See <see href="https://github.com/dotnet/roslyn/blob/main/docs/Adding%20Optional%20Parameters%20in%20Public%20API.md"/>.</remarks>
    [DiagnosticRule]
    public static class RS0026
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(RS0026);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = PublicApiCategory.ApiDesign;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/dotnet/roslyn/blob/main/docs/Adding%20Optional%20Parameters%20in%20Public%20API.md";
    }

    /// <summary>API with optional parameter(s) should have the most parameters amongst its public overloads.</summary>
    /// <remarks>See <see href="https://github.com/dotnet/roslyn/blob/main/docs/Adding%20Optional%20Parameters%20in%20Public%20API.md"/>.</remarks>
    [DiagnosticRule]
    public static class RS0027
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(RS0027);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = PublicApiCategory.ApiDesign;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/dotnet/roslyn/blob/main/docs/Adding%20Optional%20Parameters%20in%20Public%20API.md";
    }

    /// <summary>Annotate nullability of public types and members in the declared API.</summary>
    /// <remarks>See <see href="https://github.com/dotnet/roslyn/blob/main/src/RoslynAnalyzers/PublicApiAnalyzers/PublicApiAnalyzers.Help.md"/>.</remarks>
    [DiagnosticRule]
    public static class RS0036
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(RS0036);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = PublicApiCategory.ApiDesign;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/dotnet/roslyn/blob/main/src/RoslynAnalyzers/PublicApiAnalyzers/PublicApiAnalyzers.Help.md";
    }

    /// <summary>Enable tracking of nullability of reference types in the declared API.</summary>
    /// <remarks>See <see href="https://github.com/dotnet/roslyn/blob/main/src/RoslynAnalyzers/PublicApiAnalyzers/PublicApiAnalyzers.Help.md"/>.</remarks>
    [DiagnosticRule]
    public static class RS0037
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(RS0037);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = PublicApiCategory.ApiDesign;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/dotnet/roslyn/blob/main/src/RoslynAnalyzers/PublicApiAnalyzers/PublicApiAnalyzers.Help.md";
    }

    /// <summary>Public members should not use oblivious types.</summary>
    /// <remarks>See <see href="https://github.com/dotnet/roslyn/blob/main/src/RoslynAnalyzers/PublicApiAnalyzers/PublicApiAnalyzers.Help.md"/>.</remarks>
    [DiagnosticRule]
    public static class RS0041
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(RS0041);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = PublicApiCategory.ApiDesign;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/dotnet/roslyn/blob/main/src/RoslynAnalyzers/PublicApiAnalyzers/PublicApiAnalyzers.Help.md";
    }

    /// <summary>Missing shipped or unshipped public API file.</summary>
    /// <remarks>See <see href="https://github.com/dotnet/roslyn/blob/main/src/RoslynAnalyzers/PublicApiAnalyzers/PublicApiAnalyzers.Help.md"/>.</remarks>
    [DiagnosticRule]
    public static class RS0048
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(RS0048);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = PublicApiCategory.ApiDesign;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/dotnet/roslyn/blob/main/src/RoslynAnalyzers/PublicApiAnalyzers/PublicApiAnalyzers.Help.md";
    }

    /// <summary>API is marked as removed but it exists in source code.</summary>
    /// <remarks>See <see href="https://github.com/dotnet/roslyn/blob/main/src/RoslynAnalyzers/PublicApiAnalyzers/PublicApiAnalyzers.Help.md"/>.</remarks>
    [DiagnosticRule]
    public static class RS0050
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(RS0050);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = PublicApiCategory.ApiDesign;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/dotnet/roslyn/blob/main/src/RoslynAnalyzers/PublicApiAnalyzers/PublicApiAnalyzers.Help.md";
    }

    /// <summary>Add internal types and members to the declared API.</summary>
    /// <remarks>See <see href="https://github.com/dotnet/roslyn/blob/main/src/RoslynAnalyzers/PublicApiAnalyzers/PublicApiAnalyzers.Help.md"/>.</remarks>
    [DiagnosticRule]
    public static class RS0051
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(RS0051);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = PublicApiCategory.ApiDesign;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/dotnet/roslyn/blob/main/src/RoslynAnalyzers/PublicApiAnalyzers/PublicApiAnalyzers.Help.md";
    }

    /// <summary>Remove deleted types and members from the declared internal API.</summary>
    /// <remarks>See <see href="https://github.com/dotnet/roslyn/blob/main/src/RoslynAnalyzers/PublicApiAnalyzers/PublicApiAnalyzers.Help.md"/>.</remarks>
    [DiagnosticRule]
    public static class RS0052
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(RS0052);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = PublicApiCategory.ApiDesign;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/dotnet/roslyn/blob/main/src/RoslynAnalyzers/PublicApiAnalyzers/PublicApiAnalyzers.Help.md";
    }

    /// <summary>The contents of the internal API files are invalid.</summary>
    /// <remarks>See <see href="https://github.com/dotnet/roslyn/blob/main/src/RoslynAnalyzers/PublicApiAnalyzers/PublicApiAnalyzers.Help.md"/>.</remarks>
    [DiagnosticRule]
    public static class RS0053
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(RS0053);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = PublicApiCategory.ApiDesign;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/dotnet/roslyn/blob/main/src/RoslynAnalyzers/PublicApiAnalyzers/PublicApiAnalyzers.Help.md";
    }

    /// <summary>Do not duplicate symbols in internal API files.</summary>
    /// <remarks>See <see href="https://github.com/dotnet/roslyn/blob/main/src/RoslynAnalyzers/PublicApiAnalyzers/PublicApiAnalyzers.Help.md"/>.</remarks>
    [DiagnosticRule]
    public static class RS0054
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(RS0054);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = PublicApiCategory.ApiDesign;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/dotnet/roslyn/blob/main/src/RoslynAnalyzers/PublicApiAnalyzers/PublicApiAnalyzers.Help.md";
    }

    /// <summary>Annotate nullability of internal types and members in the declared API.</summary>
    /// <remarks>See <see href="https://github.com/dotnet/roslyn/blob/main/src/RoslynAnalyzers/PublicApiAnalyzers/PublicApiAnalyzers.Help.md"/>.</remarks>
    [DiagnosticRule]
    public static class RS0055
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(RS0055);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = PublicApiCategory.ApiDesign;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/dotnet/roslyn/blob/main/src/RoslynAnalyzers/PublicApiAnalyzers/PublicApiAnalyzers.Help.md";
    }

    /// <summary>Enable tracking of nullability of reference types in the declared API.</summary>
    /// <remarks>See <see href="https://github.com/dotnet/roslyn/blob/main/src/RoslynAnalyzers/PublicApiAnalyzers/PublicApiAnalyzers.Help.md"/>.</remarks>
    [DiagnosticRule]
    public static class RS0056
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(RS0056);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = PublicApiCategory.ApiDesign;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/dotnet/roslyn/blob/main/src/RoslynAnalyzers/PublicApiAnalyzers/PublicApiAnalyzers.Help.md";
    }

    /// <summary>Internal members should not use oblivious types.</summary>
    /// <remarks>See <see href="https://github.com/dotnet/roslyn/blob/main/src/RoslynAnalyzers/PublicApiAnalyzers/PublicApiAnalyzers.Help.md"/>.</remarks>
    [DiagnosticRule]
    public static class RS0057
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(RS0057);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = PublicApiCategory.ApiDesign;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/dotnet/roslyn/blob/main/src/RoslynAnalyzers/PublicApiAnalyzers/PublicApiAnalyzers.Help.md";
    }

    /// <summary>Missing shipped or unshipped internal API file.</summary>
    /// <remarks>See <see href="https://github.com/dotnet/roslyn/blob/main/src/RoslynAnalyzers/PublicApiAnalyzers/PublicApiAnalyzers.Help.md"/>.</remarks>
    [DiagnosticRule]
    public static class RS0058
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(RS0058);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = PublicApiCategory.ApiDesign;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/dotnet/roslyn/blob/main/src/RoslynAnalyzers/PublicApiAnalyzers/PublicApiAnalyzers.Help.md";
    }

    /// <summary>Do not add multiple public overloads with optional parameters.</summary>
    /// <remarks>See <see href="https://github.com/dotnet/roslyn/blob/main/docs/Adding%20Optional%20Parameters%20in%20Public%20API.md"/>.</remarks>
    [DiagnosticRule]
    public static class RS0059
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(RS0059);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = PublicApiCategory.ApiDesign;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/dotnet/roslyn/blob/main/docs/Adding%20Optional%20Parameters%20in%20Public%20API.md";
    }

    /// <summary>API with optional parameter(s) should have the most parameters amongst its public overloads.</summary>
    /// <remarks>See <see href="https://github.com/dotnet/roslyn/blob/main/docs/Adding%20Optional%20Parameters%20in%20Public%20API.md"/>.</remarks>
    [DiagnosticRule]
    public static class RS0060
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(RS0060);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = PublicApiCategory.ApiDesign;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/dotnet/roslyn/blob/main/docs/Adding%20Optional%20Parameters%20in%20Public%20API.md";
    }

    /// <summary>Constructor make noninheritable base class inheritable.</summary>
    /// <remarks>See <see href="https://github.com/dotnet/roslyn/blob/main/src/RoslynAnalyzers/PublicApiAnalyzers/PublicApiAnalyzers.Help.md"/>.</remarks>
    [DiagnosticRule]
    public static class RS0061
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(RS0061);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = PublicApiCategory.ApiDesign;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/dotnet/roslyn/blob/main/src/RoslynAnalyzers/PublicApiAnalyzers/PublicApiAnalyzers.Help.md";
    }
}
