// <auto-generated>
//     Generated by eng/CatalogGen from the DiagnosticDescriptor instances declared by
//     xunit.analyzers 1.27.0 (language: cs).
//     Do not edit by hand: rerun the generator.
//
//     Only Id, Category, Title and HelpLinkUri are emitted, and only when the
//     descriptor actually supplies them. A rule's title is reproduced verbatim as its
//     documentation comment: it is the one sentence that says what the rule is about,
//     and it is xunit.analyzers's own wording. Rule descriptions and message
//     formats are the vendor's documentation and are not redistributed here.
// </auto-generated>

using DiagnosticCatalog;

[assembly: CatalogSource(
    source:        "xunit.analyzers",
    sourceVersion: "1.27.0",
    generatedOn:   "2026-08-05")]

namespace DiagnosticCatalog.Xunit;

/// <summary>
/// The diagnostic categories used by xunit.analyzers, declared once each.
/// </summary>
/// <remarks>
/// INTERNAL by design. A category is reachable only through the rule that carries it:
/// write <c>SomeRule.Sxxxx.Category</c>, never the category constant directly. The two
/// spellings fold to the same string today and stop agreeing the day the vendor moves the
/// rule to another category -- the rule member follows, a category named on its own does
/// not, and the suppression silently stops matching. Keeping this class out of the public
/// surface makes that decoupling unwritable rather than merely discouraged.
/// The public <c>Category</c> constant on each rule is initialised from here and folds to
/// the literal at compile time, so a consumer loses nothing.
/// </remarks>
[DiagnosticCategory]
internal static class XunitCategory
{
    /// <summary>The <c>Assertions</c> category.</summary>
    public const string Assertions = "Assertions";

    /// <summary>The <c>Extensibility</c> category.</summary>
    public const string Extensibility = "Extensibility";

    /// <summary>The <c>Usage</c> category.</summary>
    public const string Usage = "Usage";
}

/// <summary>
/// The xunit.analyzers diagnostic rules, as declared by that package's analyzers.
/// </summary>
public static class XunitRule
{
    /// <summary>Test classes must be public.</summary>
    /// <remarks>See <see href="https://xunit.net/xunit.analyzers/rules/xUnit1000"/>.</remarks>
    [DiagnosticRule]
    public static class xUnit1000
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(xUnit1000);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = XunitCategory.Usage;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://xunit.net/xunit.analyzers/rules/xUnit1000";
    }

    /// <summary>Fact methods cannot have parameters.</summary>
    /// <remarks>See <see href="https://xunit.net/xunit.analyzers/rules/xUnit1001"/>.</remarks>
    [DiagnosticRule]
    public static class xUnit1001
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(xUnit1001);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = XunitCategory.Usage;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://xunit.net/xunit.analyzers/rules/xUnit1001";
    }

    /// <summary>Test methods cannot have multiple Fact or Theory attributes.</summary>
    /// <remarks>See <see href="https://xunit.net/xunit.analyzers/rules/xUnit1002"/>.</remarks>
    [DiagnosticRule]
    public static class xUnit1002
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(xUnit1002);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = XunitCategory.Usage;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://xunit.net/xunit.analyzers/rules/xUnit1002";
    }

    /// <summary>Theory methods must have test data.</summary>
    /// <remarks>See <see href="https://xunit.net/xunit.analyzers/rules/xUnit1003"/>.</remarks>
    [DiagnosticRule]
    public static class xUnit1003
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(xUnit1003);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = XunitCategory.Usage;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://xunit.net/xunit.analyzers/rules/xUnit1003";
    }

    /// <summary>Test methods should not be skipped.</summary>
    /// <remarks>See <see href="https://xunit.net/xunit.analyzers/rules/xUnit1004"/>.</remarks>
    [DiagnosticRule]
    public static class xUnit1004
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(xUnit1004);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = XunitCategory.Usage;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://xunit.net/xunit.analyzers/rules/xUnit1004";
    }

    /// <summary>Fact methods should not have test data.</summary>
    /// <remarks>See <see href="https://xunit.net/xunit.analyzers/rules/xUnit1005"/>.</remarks>
    [DiagnosticRule]
    public static class xUnit1005
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(xUnit1005);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = XunitCategory.Usage;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://xunit.net/xunit.analyzers/rules/xUnit1005";
    }

    /// <summary>Theory methods should have parameters.</summary>
    /// <remarks>See <see href="https://xunit.net/xunit.analyzers/rules/xUnit1006"/>.</remarks>
    [DiagnosticRule]
    public static class xUnit1006
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(xUnit1006);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = XunitCategory.Usage;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://xunit.net/xunit.analyzers/rules/xUnit1006";
    }

    /// <summary>ClassData must point at a valid class.</summary>
    /// <remarks>See <see href="https://xunit.net/xunit.analyzers/rules/xUnit1007"/>.</remarks>
    [DiagnosticRule]
    public static class xUnit1007
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(xUnit1007);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = XunitCategory.Usage;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://xunit.net/xunit.analyzers/rules/xUnit1007";
    }

    /// <summary>Test data attribute should only be used on a Theory.</summary>
    /// <remarks>See <see href="https://xunit.net/xunit.analyzers/rules/xUnit1008"/>.</remarks>
    [DiagnosticRule]
    public static class xUnit1008
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(xUnit1008);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = XunitCategory.Usage;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://xunit.net/xunit.analyzers/rules/xUnit1008";
    }

    /// <summary>InlineData values must match the number of method parameters.</summary>
    /// <remarks>See <see href="https://xunit.net/xunit.analyzers/rules/xUnit1009"/>.</remarks>
    [DiagnosticRule]
    public static class xUnit1009
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(xUnit1009);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = XunitCategory.Usage;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://xunit.net/xunit.analyzers/rules/xUnit1009";
    }

    /// <summary>The value is not convertible to the method parameter type.</summary>
    /// <remarks>See <see href="https://xunit.net/xunit.analyzers/rules/xUnit1010"/>.</remarks>
    [DiagnosticRule]
    public static class xUnit1010
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(xUnit1010);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = XunitCategory.Usage;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://xunit.net/xunit.analyzers/rules/xUnit1010";
    }

    /// <summary>There is no matching method parameter.</summary>
    /// <remarks>See <see href="https://xunit.net/xunit.analyzers/rules/xUnit1011"/>.</remarks>
    [DiagnosticRule]
    public static class xUnit1011
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(xUnit1011);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = XunitCategory.Usage;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://xunit.net/xunit.analyzers/rules/xUnit1011";
    }

    /// <summary>Null should only be used for nullable parameters.</summary>
    /// <remarks>See <see href="https://xunit.net/xunit.analyzers/rules/xUnit1012"/>.</remarks>
    [DiagnosticRule]
    public static class xUnit1012
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(xUnit1012);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = XunitCategory.Usage;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://xunit.net/xunit.analyzers/rules/xUnit1012";
    }

    /// <summary>Public method should be marked as test.</summary>
    /// <remarks>See <see href="https://xunit.net/xunit.analyzers/rules/xUnit1013"/>.</remarks>
    [DiagnosticRule]
    public static class xUnit1013
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(xUnit1013);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = XunitCategory.Usage;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://xunit.net/xunit.analyzers/rules/xUnit1013";
    }

    /// <summary>MemberData should use nameof operator for member name.</summary>
    /// <remarks>See <see href="https://xunit.net/xunit.analyzers/rules/xUnit1014"/>.</remarks>
    [DiagnosticRule]
    public static class xUnit1014
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(xUnit1014);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = XunitCategory.Usage;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://xunit.net/xunit.analyzers/rules/xUnit1014";
    }

    /// <summary>MemberData must reference an existing member.</summary>
    /// <remarks>See <see href="https://xunit.net/xunit.analyzers/rules/xUnit1015"/>.</remarks>
    [DiagnosticRule]
    public static class xUnit1015
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(xUnit1015);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = XunitCategory.Usage;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://xunit.net/xunit.analyzers/rules/xUnit1015";
    }

    /// <summary>MemberData must reference a public member.</summary>
    /// <remarks>See <see href="https://xunit.net/xunit.analyzers/rules/xUnit1016"/>.</remarks>
    [DiagnosticRule]
    public static class xUnit1016
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(xUnit1016);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = XunitCategory.Usage;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://xunit.net/xunit.analyzers/rules/xUnit1016";
    }

    /// <summary>MemberData must reference a static member.</summary>
    /// <remarks>See <see href="https://xunit.net/xunit.analyzers/rules/xUnit1017"/>.</remarks>
    [DiagnosticRule]
    public static class xUnit1017
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(xUnit1017);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = XunitCategory.Usage;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://xunit.net/xunit.analyzers/rules/xUnit1017";
    }

    /// <summary>MemberData must reference a valid member kind.</summary>
    /// <remarks>See <see href="https://xunit.net/xunit.analyzers/rules/xUnit1018"/>.</remarks>
    [DiagnosticRule]
    public static class xUnit1018
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(xUnit1018);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = XunitCategory.Usage;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://xunit.net/xunit.analyzers/rules/xUnit1018";
    }

    /// <summary>MemberData must reference a member providing a valid data type.</summary>
    /// <remarks>See <see href="https://xunit.net/xunit.analyzers/rules/xUnit1019"/>.</remarks>
    [DiagnosticRule]
    public static class xUnit1019
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(xUnit1019);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = XunitCategory.Usage;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://xunit.net/xunit.analyzers/rules/xUnit1019";
    }

    /// <summary>MemberData must reference a property with a public getter.</summary>
    /// <remarks>See <see href="https://xunit.net/xunit.analyzers/rules/xUnit1020"/>.</remarks>
    [DiagnosticRule]
    public static class xUnit1020
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(xUnit1020);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = XunitCategory.Usage;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://xunit.net/xunit.analyzers/rules/xUnit1020";
    }

    /// <summary>MemberData should not have parameters if the referenced member is not a method.</summary>
    /// <remarks>See <see href="https://xunit.net/xunit.analyzers/rules/xUnit1021"/>.</remarks>
    [DiagnosticRule]
    public static class xUnit1021
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(xUnit1021);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = XunitCategory.Usage;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://xunit.net/xunit.analyzers/rules/xUnit1021";
    }

    /// <summary>Theory methods cannot have a parameter array.</summary>
    /// <remarks>See <see href="https://xunit.net/xunit.analyzers/rules/xUnit1022"/>.</remarks>
    [DiagnosticRule]
    public static class xUnit1022
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(xUnit1022);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = XunitCategory.Usage;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://xunit.net/xunit.analyzers/rules/xUnit1022";
    }

    /// <summary>Theory methods cannot have default parameter values.</summary>
    /// <remarks>See <see href="https://xunit.net/xunit.analyzers/rules/xUnit1023"/>.</remarks>
    [DiagnosticRule]
    public static class xUnit1023
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(xUnit1023);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = XunitCategory.Usage;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://xunit.net/xunit.analyzers/rules/xUnit1023";
    }

    /// <summary>Test methods cannot have overloads.</summary>
    /// <remarks>See <see href="https://xunit.net/xunit.analyzers/rules/xUnit1024"/>.</remarks>
    [DiagnosticRule]
    public static class xUnit1024
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(xUnit1024);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = XunitCategory.Usage;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://xunit.net/xunit.analyzers/rules/xUnit1024";
    }

    /// <summary>InlineData should be unique within the Theory it belongs to.</summary>
    /// <remarks>See <see href="https://xunit.net/xunit.analyzers/rules/xUnit1025"/>.</remarks>
    [DiagnosticRule]
    public static class xUnit1025
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(xUnit1025);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = XunitCategory.Usage;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://xunit.net/xunit.analyzers/rules/xUnit1025";
    }

    /// <summary>Theory methods should use all of their parameters.</summary>
    /// <remarks>See <see href="https://xunit.net/xunit.analyzers/rules/xUnit1026"/>.</remarks>
    [DiagnosticRule]
    public static class xUnit1026
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(xUnit1026);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = XunitCategory.Usage;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://xunit.net/xunit.analyzers/rules/xUnit1026";
    }

    /// <summary>Collection definition classes must be public.</summary>
    /// <remarks>See <see href="https://xunit.net/xunit.analyzers/rules/xUnit1027"/>.</remarks>
    [DiagnosticRule]
    public static class xUnit1027
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(xUnit1027);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = XunitCategory.Usage;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://xunit.net/xunit.analyzers/rules/xUnit1027";
    }

    /// <summary>Test method must have valid return type.</summary>
    /// <remarks>See <see href="https://xunit.net/xunit.analyzers/rules/xUnit1028"/>.</remarks>
    [DiagnosticRule]
    public static class xUnit1028
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(xUnit1028);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = XunitCategory.Usage;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://xunit.net/xunit.analyzers/rules/xUnit1028";
    }

    /// <summary>Local functions cannot be test functions.</summary>
    /// <remarks>See <see href="https://xunit.net/xunit.analyzers/rules/xUnit1029"/>.</remarks>
    [DiagnosticRule]
    public static class xUnit1029
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(xUnit1029);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = XunitCategory.Usage;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://xunit.net/xunit.analyzers/rules/xUnit1029";
    }

    /// <summary>Do not call ConfigureAwait(false) in test method.</summary>
    /// <remarks>See <see href="https://xunit.net/xunit.analyzers/rules/xUnit1030"/>.</remarks>
    [DiagnosticRule]
    public static class xUnit1030
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(xUnit1030);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = XunitCategory.Usage;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://xunit.net/xunit.analyzers/rules/xUnit1030";
    }

    /// <summary>Do not use blocking task operations in test method.</summary>
    /// <remarks>See <see href="https://xunit.net/xunit.analyzers/rules/xUnit1031"/>.</remarks>
    [DiagnosticRule]
    public static class xUnit1031
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(xUnit1031);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = XunitCategory.Usage;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://xunit.net/xunit.analyzers/rules/xUnit1031";
    }

    /// <summary>Test classes cannot be nested within a generic class.</summary>
    /// <remarks>See <see href="https://xunit.net/xunit.analyzers/rules/xUnit1032"/>.</remarks>
    [DiagnosticRule]
    public static class xUnit1032
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(xUnit1032);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = XunitCategory.Usage;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://xunit.net/xunit.analyzers/rules/xUnit1032";
    }

    /// <summary>Test classes decorated with 'Xunit.IClassFixture&lt;TFixture&gt;' or 'Xunit.ICollectionFixture&lt;TFixture&gt;' should add a constructor argument of type TFixture.</summary>
    /// <remarks>See <see href="https://xunit.net/xunit.analyzers/rules/xUnit1033"/>.</remarks>
    [DiagnosticRule]
    public static class xUnit1033
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(xUnit1033);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = XunitCategory.Usage;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://xunit.net/xunit.analyzers/rules/xUnit1033";
    }

    /// <summary>Null should only be used for nullable parameters.</summary>
    /// <remarks>See <see href="https://xunit.net/xunit.analyzers/rules/xUnit1034"/>.</remarks>
    [DiagnosticRule]
    public static class xUnit1034
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(xUnit1034);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = XunitCategory.Usage;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://xunit.net/xunit.analyzers/rules/xUnit1034";
    }

    /// <summary>The value is not convertible to the method parameter type.</summary>
    /// <remarks>See <see href="https://xunit.net/xunit.analyzers/rules/xUnit1035"/>.</remarks>
    [DiagnosticRule]
    public static class xUnit1035
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(xUnit1035);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = XunitCategory.Usage;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://xunit.net/xunit.analyzers/rules/xUnit1035";
    }

    /// <summary>There is no matching method parameter.</summary>
    /// <remarks>See <see href="https://xunit.net/xunit.analyzers/rules/xUnit1036"/>.</remarks>
    [DiagnosticRule]
    public static class xUnit1036
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(xUnit1036);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = XunitCategory.Usage;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://xunit.net/xunit.analyzers/rules/xUnit1036";
    }

    /// <summary>There are fewer theory data type arguments than required by the parameters of the test method.</summary>
    /// <remarks>See <see href="https://xunit.net/xunit.analyzers/rules/xUnit1037"/>.</remarks>
    [DiagnosticRule]
    public static class xUnit1037
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(xUnit1037);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = XunitCategory.Usage;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://xunit.net/xunit.analyzers/rules/xUnit1037";
    }

    /// <summary>There are more theory data type arguments than allowed by the parameters of the test method.</summary>
    /// <remarks>See <see href="https://xunit.net/xunit.analyzers/rules/xUnit1038"/>.</remarks>
    [DiagnosticRule]
    public static class xUnit1038
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(xUnit1038);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = XunitCategory.Usage;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://xunit.net/xunit.analyzers/rules/xUnit1038";
    }

    /// <summary>The type argument to theory data is not compatible with the type of the corresponding test method parameter.</summary>
    /// <remarks>See <see href="https://xunit.net/xunit.analyzers/rules/xUnit1039"/>.</remarks>
    [DiagnosticRule]
    public static class xUnit1039
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(xUnit1039);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = XunitCategory.Usage;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://xunit.net/xunit.analyzers/rules/xUnit1039";
    }

    /// <summary>The type argument to theory data is nullable, while the type of the corresponding test method parameter is not.</summary>
    /// <remarks>See <see href="https://xunit.net/xunit.analyzers/rules/xUnit1040"/>.</remarks>
    [DiagnosticRule]
    public static class xUnit1040
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(xUnit1040);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = XunitCategory.Usage;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://xunit.net/xunit.analyzers/rules/xUnit1040";
    }

    /// <summary>Fixture arguments to test classes must have fixture sources.</summary>
    /// <remarks>See <see href="https://xunit.net/xunit.analyzers/rules/xUnit1041"/>.</remarks>
    [DiagnosticRule]
    public static class xUnit1041
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(xUnit1041);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = XunitCategory.Usage;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://xunit.net/xunit.analyzers/rules/xUnit1041";
    }

    /// <summary>The member referenced by the MemberData attribute returns untyped data rows.</summary>
    /// <remarks>See <see href="https://xunit.net/xunit.analyzers/rules/xUnit1042"/>.</remarks>
    [DiagnosticRule]
    public static class xUnit1042
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(xUnit1042);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = XunitCategory.Usage;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://xunit.net/xunit.analyzers/rules/xUnit1042";
    }

    /// <summary>Constructors on classes derived from FactAttribute must be public when used on test methods.</summary>
    /// <remarks>See <see href="https://xunit.net/xunit.analyzers/rules/xUnit1043"/>.</remarks>
    [DiagnosticRule]
    public static class xUnit1043
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(xUnit1043);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = XunitCategory.Usage;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://xunit.net/xunit.analyzers/rules/xUnit1043";
    }

    /// <summary>Avoid using TheoryData type arguments that are not serializable.</summary>
    /// <remarks>See <see href="https://xunit.net/xunit.analyzers/rules/xUnit1044"/>.</remarks>
    [DiagnosticRule]
    public static class xUnit1044
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(xUnit1044);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = XunitCategory.Usage;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://xunit.net/xunit.analyzers/rules/xUnit1044";
    }

    /// <summary>Avoid using TheoryData type arguments that might not be serializable.</summary>
    /// <remarks>See <see href="https://xunit.net/xunit.analyzers/rules/xUnit1045"/>.</remarks>
    [DiagnosticRule]
    public static class xUnit1045
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(xUnit1045);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = XunitCategory.Usage;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://xunit.net/xunit.analyzers/rules/xUnit1045";
    }

    /// <summary>Avoid using TheoryDataRow arguments that are not serializable.</summary>
    /// <remarks>See <see href="https://xunit.net/xunit.analyzers/rules/xUnit1046"/>.</remarks>
    [DiagnosticRule]
    public static class xUnit1046
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(xUnit1046);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = XunitCategory.Usage;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://xunit.net/xunit.analyzers/rules/xUnit1046";
    }

    /// <summary>Avoid using TheoryDataRow arguments that might not be serializable.</summary>
    /// <remarks>See <see href="https://xunit.net/xunit.analyzers/rules/xUnit1047"/>.</remarks>
    [DiagnosticRule]
    public static class xUnit1047
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(xUnit1047);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = XunitCategory.Usage;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://xunit.net/xunit.analyzers/rules/xUnit1047";
    }

    /// <summary>Avoid using 'async void' for test methods as it is deprecated in xUnit.net v3.</summary>
    /// <remarks>See <see href="https://xunit.net/xunit.analyzers/rules/xUnit1048"/>.</remarks>
    [DiagnosticRule]
    public static class xUnit1048
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(xUnit1048);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = XunitCategory.Usage;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://xunit.net/xunit.analyzers/rules/xUnit1048";
    }

    /// <summary>Do not use 'async void' for test methods as it is no longer supported.</summary>
    /// <remarks>See <see href="https://xunit.net/xunit.analyzers/rules/xUnit1049"/>.</remarks>
    [DiagnosticRule]
    public static class xUnit1049
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(xUnit1049);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = XunitCategory.Usage;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://xunit.net/xunit.analyzers/rules/xUnit1049";
    }

    /// <summary>The class referenced by the ClassData attribute returns untyped data rows.</summary>
    /// <remarks>See <see href="https://xunit.net/xunit.analyzers/rules/xUnit1050"/>.</remarks>
    [DiagnosticRule]
    public static class xUnit1050
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(xUnit1050);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = XunitCategory.Usage;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://xunit.net/xunit.analyzers/rules/xUnit1050";
    }

    /// <summary>Calls to methods which accept CancellationToken should use TestContext.Current.CancellationToken.</summary>
    /// <remarks>See <see href="https://xunit.net/xunit.analyzers/rules/xUnit1051"/>.</remarks>
    [DiagnosticRule]
    public static class xUnit1051
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(xUnit1051);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = XunitCategory.Usage;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://xunit.net/xunit.analyzers/rules/xUnit1051";
    }

    /// <summary>Avoid using 'TheoryData&lt;...&gt;' with types that implement 'ITheoryDataRow'.</summary>
    /// <remarks>See <see href="https://xunit.net/xunit.analyzers/rules/xUnit1052"/>.</remarks>
    [DiagnosticRule]
    public static class xUnit1052
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(xUnit1052);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = XunitCategory.Usage;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://xunit.net/xunit.analyzers/rules/xUnit1052";
    }

    /// <summary>The static member used as theory data must be statically initialized.</summary>
    /// <remarks>See <see href="https://xunit.net/xunit.analyzers/rules/xUnit1053"/>.</remarks>
    [DiagnosticRule]
    public static class xUnit1053
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(xUnit1053);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = XunitCategory.Usage;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://xunit.net/xunit.analyzers/rules/xUnit1053";
    }

    /// <summary>Constants and literals should be the expected argument.</summary>
    /// <remarks>See <see href="https://xunit.net/xunit.analyzers/rules/xUnit2000"/>.</remarks>
    [DiagnosticRule]
    public static class xUnit2000
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(xUnit2000);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = XunitCategory.Assertions;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://xunit.net/xunit.analyzers/rules/xUnit2000";
    }

    /// <summary>Do not use invalid equality check.</summary>
    /// <remarks>See <see href="https://xunit.net/xunit.analyzers/rules/xUnit2001"/>.</remarks>
    [DiagnosticRule]
    public static class xUnit2001
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(xUnit2001);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = XunitCategory.Assertions;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://xunit.net/xunit.analyzers/rules/xUnit2001";
    }

    /// <summary>Do not use null check on value type.</summary>
    /// <remarks>See <see href="https://xunit.net/xunit.analyzers/rules/xUnit2002"/>.</remarks>
    [DiagnosticRule]
    public static class xUnit2002
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(xUnit2002);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = XunitCategory.Assertions;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://xunit.net/xunit.analyzers/rules/xUnit2002";
    }

    /// <summary>Do not use equality check to test for null value.</summary>
    /// <remarks>See <see href="https://xunit.net/xunit.analyzers/rules/xUnit2003"/>.</remarks>
    [DiagnosticRule]
    public static class xUnit2003
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(xUnit2003);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = XunitCategory.Assertions;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://xunit.net/xunit.analyzers/rules/xUnit2003";
    }

    /// <summary>Do not use equality check to test for boolean conditions.</summary>
    /// <remarks>See <see href="https://xunit.net/xunit.analyzers/rules/xUnit2004"/>.</remarks>
    [DiagnosticRule]
    public static class xUnit2004
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(xUnit2004);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = XunitCategory.Assertions;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://xunit.net/xunit.analyzers/rules/xUnit2004";
    }

    /// <summary>Do not use identity check on value type.</summary>
    /// <remarks>See <see href="https://xunit.net/xunit.analyzers/rules/xUnit2005"/>.</remarks>
    [DiagnosticRule]
    public static class xUnit2005
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(xUnit2005);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = XunitCategory.Assertions;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://xunit.net/xunit.analyzers/rules/xUnit2005";
    }

    /// <summary>Do not use invalid string equality check.</summary>
    /// <remarks>See <see href="https://xunit.net/xunit.analyzers/rules/xUnit2006"/>.</remarks>
    [DiagnosticRule]
    public static class xUnit2006
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(xUnit2006);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = XunitCategory.Assertions;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://xunit.net/xunit.analyzers/rules/xUnit2006";
    }

    /// <summary>Do not use typeof expression to check the type.</summary>
    /// <remarks>See <see href="https://xunit.net/xunit.analyzers/rules/xUnit2007"/>.</remarks>
    [DiagnosticRule]
    public static class xUnit2007
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(xUnit2007);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = XunitCategory.Assertions;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://xunit.net/xunit.analyzers/rules/xUnit2007";
    }

    /// <summary>Do not use boolean check to match on regular expressions.</summary>
    /// <remarks>See <see href="https://xunit.net/xunit.analyzers/rules/xUnit2008"/>.</remarks>
    [DiagnosticRule]
    public static class xUnit2008
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(xUnit2008);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = XunitCategory.Assertions;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://xunit.net/xunit.analyzers/rules/xUnit2008";
    }

    /// <summary>Do not use boolean check to check for substrings.</summary>
    /// <remarks>See <see href="https://xunit.net/xunit.analyzers/rules/xUnit2009"/>.</remarks>
    [DiagnosticRule]
    public static class xUnit2009
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(xUnit2009);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = XunitCategory.Assertions;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://xunit.net/xunit.analyzers/rules/xUnit2009";
    }

    /// <summary>Do not use boolean check to check for string equality.</summary>
    /// <remarks>See <see href="https://xunit.net/xunit.analyzers/rules/xUnit2010"/>.</remarks>
    [DiagnosticRule]
    public static class xUnit2010
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(xUnit2010);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = XunitCategory.Assertions;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://xunit.net/xunit.analyzers/rules/xUnit2010";
    }

    /// <summary>Do not use empty collection check.</summary>
    /// <remarks>See <see href="https://xunit.net/xunit.analyzers/rules/xUnit2011"/>.</remarks>
    [DiagnosticRule]
    public static class xUnit2011
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(xUnit2011);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = XunitCategory.Assertions;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://xunit.net/xunit.analyzers/rules/xUnit2011";
    }

    /// <summary>Do not use boolean check to check if a value exists in a collection.</summary>
    /// <remarks>See <see href="https://xunit.net/xunit.analyzers/rules/xUnit2012"/>.</remarks>
    [DiagnosticRule]
    public static class xUnit2012
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(xUnit2012);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = XunitCategory.Assertions;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://xunit.net/xunit.analyzers/rules/xUnit2012";
    }

    /// <summary>Do not use equality check to check for collection size.</summary>
    /// <remarks>See <see href="https://xunit.net/xunit.analyzers/rules/xUnit2013"/>.</remarks>
    [DiagnosticRule]
    public static class xUnit2013
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(xUnit2013);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = XunitCategory.Assertions;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://xunit.net/xunit.analyzers/rules/xUnit2013";
    }

    /// <summary>Do not use throws check to check for asynchronously thrown exception.</summary>
    /// <remarks>See <see href="https://xunit.net/xunit.analyzers/rules/xUnit2014"/>.</remarks>
    [DiagnosticRule]
    public static class xUnit2014
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(xUnit2014);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = XunitCategory.Assertions;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://xunit.net/xunit.analyzers/rules/xUnit2014";
    }

    /// <summary>Do not use typeof expression to check the exception type.</summary>
    /// <remarks>See <see href="https://xunit.net/xunit.analyzers/rules/xUnit2015"/>.</remarks>
    [DiagnosticRule]
    public static class xUnit2015
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(xUnit2015);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = XunitCategory.Assertions;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://xunit.net/xunit.analyzers/rules/xUnit2015";
    }

    /// <summary>Keep precision in the allowed range when asserting equality of doubles or decimals.</summary>
    /// <remarks>See <see href="https://xunit.net/xunit.analyzers/rules/xUnit2016"/>.</remarks>
    [DiagnosticRule]
    public static class xUnit2016
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(xUnit2016);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = XunitCategory.Assertions;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://xunit.net/xunit.analyzers/rules/xUnit2016";
    }

    /// <summary>Do not use Contains() to check if a value exists in a collection.</summary>
    /// <remarks>See <see href="https://xunit.net/xunit.analyzers/rules/xUnit2017"/>.</remarks>
    [DiagnosticRule]
    public static class xUnit2017
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(xUnit2017);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = XunitCategory.Assertions;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://xunit.net/xunit.analyzers/rules/xUnit2017";
    }

    /// <summary>Do not compare an object's exact type to an abstract class or interface.</summary>
    /// <remarks>See <see href="https://xunit.net/xunit.analyzers/rules/xUnit2018"/>.</remarks>
    [DiagnosticRule]
    public static class xUnit2018
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(xUnit2018);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = XunitCategory.Assertions;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://xunit.net/xunit.analyzers/rules/xUnit2018";
    }

    /// <summary>Do not use always-failing boolean assertions.</summary>
    /// <remarks>See <see href="https://xunit.net/xunit.analyzers/rules/xUnit2020"/>.</remarks>
    [DiagnosticRule]
    public static class xUnit2020
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(xUnit2020);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = XunitCategory.Assertions;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://xunit.net/xunit.analyzers/rules/xUnit2020";
    }

    /// <summary>Async assertions should be awaited.</summary>
    /// <remarks>See <see href="https://xunit.net/xunit.analyzers/rules/xUnit2021"/>.</remarks>
    [DiagnosticRule]
    public static class xUnit2021
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(xUnit2021);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = XunitCategory.Assertions;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://xunit.net/xunit.analyzers/rules/xUnit2021";
    }

    /// <summary>Boolean assertions should not be negated.</summary>
    /// <remarks>See <see href="https://xunit.net/xunit.analyzers/rules/xUnit2022"/>.</remarks>
    [DiagnosticRule]
    public static class xUnit2022
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(xUnit2022);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = XunitCategory.Assertions;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://xunit.net/xunit.analyzers/rules/xUnit2022";
    }

    /// <summary>Do not use collection methods for single-item collections.</summary>
    /// <remarks>See <see href="https://xunit.net/xunit.analyzers/rules/xUnit2023"/>.</remarks>
    [DiagnosticRule]
    public static class xUnit2023
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(xUnit2023);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = XunitCategory.Assertions;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://xunit.net/xunit.analyzers/rules/xUnit2023";
    }

    /// <summary>Do not use boolean asserts for simple equality tests.</summary>
    /// <remarks>See <see href="https://xunit.net/xunit.analyzers/rules/xUnit2024"/>.</remarks>
    [DiagnosticRule]
    public static class xUnit2024
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(xUnit2024);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = XunitCategory.Assertions;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://xunit.net/xunit.analyzers/rules/xUnit2024";
    }

    /// <summary>The boolean assertion statement can be simplified.</summary>
    /// <remarks>See <see href="https://xunit.net/xunit.analyzers/rules/xUnit2025"/>.</remarks>
    [DiagnosticRule]
    public static class xUnit2025
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(xUnit2025);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = XunitCategory.Assertions;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://xunit.net/xunit.analyzers/rules/xUnit2025";
    }

    /// <summary>Comparison of sets must be done with IEqualityComparer.</summary>
    /// <remarks>See <see href="https://xunit.net/xunit.analyzers/rules/xUnit2026"/>.</remarks>
    [DiagnosticRule]
    public static class xUnit2026
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(xUnit2026);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = XunitCategory.Assertions;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://xunit.net/xunit.analyzers/rules/xUnit2026";
    }

    /// <summary>Comparison of sets to linear containers have undefined results.</summary>
    /// <remarks>See <see href="https://xunit.net/xunit.analyzers/rules/xUnit2027"/>.</remarks>
    [DiagnosticRule]
    public static class xUnit2027
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(xUnit2027);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = XunitCategory.Assertions;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://xunit.net/xunit.analyzers/rules/xUnit2027";
    }

    /// <summary>Do not use Assert.Empty or Assert.NotEmpty with problematic types.</summary>
    /// <remarks>See <see href="https://xunit.net/xunit.analyzers/rules/xUnit2028"/>.</remarks>
    [DiagnosticRule]
    public static class xUnit2028
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(xUnit2028);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = XunitCategory.Assertions;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://xunit.net/xunit.analyzers/rules/xUnit2028";
    }

    /// <summary>Do not use Assert.Empty to check if a value does not exist in a collection.</summary>
    /// <remarks>See <see href="https://xunit.net/xunit.analyzers/rules/xUnit2029"/>.</remarks>
    [DiagnosticRule]
    public static class xUnit2029
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(xUnit2029);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = XunitCategory.Assertions;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://xunit.net/xunit.analyzers/rules/xUnit2029";
    }

    /// <summary>Do not use Assert.NotEmpty to check if a value exists in a collection.</summary>
    /// <remarks>See <see href="https://xunit.net/xunit.analyzers/rules/xUnit2030"/>.</remarks>
    [DiagnosticRule]
    public static class xUnit2030
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(xUnit2030);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = XunitCategory.Assertions;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://xunit.net/xunit.analyzers/rules/xUnit2030";
    }

    /// <summary>Do not use Where clause with Assert.Single.</summary>
    /// <remarks>See <see href="https://xunit.net/xunit.analyzers/rules/xUnit2031"/>.</remarks>
    [DiagnosticRule]
    public static class xUnit2031
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(xUnit2031);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = XunitCategory.Assertions;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://xunit.net/xunit.analyzers/rules/xUnit2031";
    }

    /// <summary>Type assertions based on 'assignable from' are confusingly named.</summary>
    /// <remarks>See <see href="https://xunit.net/xunit.analyzers/rules/xUnit2032"/>.</remarks>
    [DiagnosticRule]
    public static class xUnit2032
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(xUnit2032);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = XunitCategory.Assertions;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://xunit.net/xunit.analyzers/rules/xUnit2032";
    }

    /// <summary>Classes which cross AppDomain boundaries must derive directly or indirectly from LongLivedMarshalByRefObject.</summary>
    /// <remarks>See <see href="https://xunit.net/xunit.analyzers/rules/xUnit3000"/>.</remarks>
    [DiagnosticRule]
    public static class xUnit3000
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(xUnit3000);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = XunitCategory.Extensibility;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://xunit.net/xunit.analyzers/rules/xUnit3000";
    }

    /// <summary>Classes that are marked as serializable (or created by the test framework at runtime) must have a public parameterless constructor.</summary>
    /// <remarks>See <see href="https://xunit.net/xunit.analyzers/rules/xUnit3001"/>.</remarks>
    [DiagnosticRule]
    public static class xUnit3001
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(xUnit3001);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = XunitCategory.Extensibility;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://xunit.net/xunit.analyzers/rules/xUnit3001";
    }

    /// <summary>Classes which are JSON serializable should not be tested for their concrete type.</summary>
    /// <remarks>See <see href="https://xunit.net/xunit.analyzers/rules/xUnit3002"/>.</remarks>
    [DiagnosticRule]
    public static class xUnit3002
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(xUnit3002);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = XunitCategory.Extensibility;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://xunit.net/xunit.analyzers/rules/xUnit3002";
    }

    /// <summary>Classes which extend FactAttribute (directly or indirectly) should provide a public constructor for source information.</summary>
    /// <remarks>See <see href="https://xunit.net/xunit.analyzers/rules/xUnit3003"/>.</remarks>
    [DiagnosticRule]
    public static class xUnit3003
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(xUnit3003);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = XunitCategory.Extensibility;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://xunit.net/xunit.analyzers/rules/xUnit3003";
    }
}
