// <auto-generated>
//     Generated by eng/CatalogGen from the DiagnosticDescriptor instances declared by
//     Microsoft.AspNetCore.App.Ref 10.0.10 (language: cs).
//     Do not edit by hand: rerun the generator.
//
//     Only Id, Category, Title and HelpLinkUri are emitted, and only when the
//     descriptor actually supplies them. A rule's title is reproduced verbatim as its
//     documentation comment: it is the one sentence that says what the rule is about,
//     and it is Microsoft.AspNetCore.App.Ref's own wording. Rule descriptions and message
//     formats are the vendor's documentation and are not redistributed here.
// </auto-generated>

using DiagnosticCatalog;

[assembly: CatalogSource(
    source:        "Microsoft.AspNetCore.App.Ref",
    sourceVersion: "10.0.10",
    generatedOn:   "2026-08-05")]

namespace DiagnosticCatalog.AspNetCore;

/// <summary>
/// The diagnostic categories used by Microsoft.AspNetCore.App.Ref, declared once each.
/// </summary>
/// <remarks>
/// INTERNAL by design. A category is reachable only through the rule that carries it:
/// write <c>SomeRule.Sxxxx.Category</c>, never the category constant directly. The two
/// spellings fold to the same string today and stop agreeing the day the vendor moves the
/// rule to another category -- the rule member follows, a category named on its own does
/// not, and the suppression is left asserting a category the rule no longer carries.
/// Nothing reports that: Roslyn ignores the category when it matches a suppression, so the
/// mistake has no symptom at all. Keeping this class out of the public surface makes that
/// decoupling unwritable rather than merely discouraged.
/// The public <c>Category</c> constant on each rule is initialised from here and folds to
/// the literal at compile time, so a consumer loses nothing.
/// </remarks>
[DiagnosticCategory]
internal static class AspNetCoreCategory
{
    /// <summary>The <c>Encapsulation</c> category.</summary>
    public const string Encapsulation = "Encapsulation";

    /// <summary>The <c>Security</c> category.</summary>
    public const string Security = "Security";

    /// <summary>The <c>Usage</c> category.</summary>
    public const string Usage = "Usage";
}

/// <summary>
/// The Microsoft.AspNetCore.App.Ref diagnostic rules, as declared by that package's analyzers.
/// </summary>
public static class AspNetCoreRule
{
    /// <summary>Do not use model binding attributes with route handlers.</summary>
    /// <remarks>See <see href="https://aka.ms/aspnet/analyzers"/>.</remarks>
    [DiagnosticRule]
    public static class ASP0003
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(ASP0003);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = AspNetCoreCategory.Usage;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://aka.ms/aspnet/analyzers";
    }

    /// <summary>Do not use action results with route handlers.</summary>
    /// <remarks>See <see href="https://aka.ms/aspnet/analyzers"/>.</remarks>
    [DiagnosticRule]
    public static class ASP0004
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(ASP0004);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = AspNetCoreCategory.Usage;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://aka.ms/aspnet/analyzers";
    }

    /// <summary>Do not place attribute on method called by route handler lambda.</summary>
    /// <remarks>See <see href="https://aka.ms/aspnet/analyzers"/>.</remarks>
    [DiagnosticRule]
    public static class ASP0005
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(ASP0005);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = AspNetCoreCategory.Usage;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://aka.ms/aspnet/analyzers";
    }

    /// <summary>Do not use non-literal sequence numbers.</summary>
    /// <remarks>See <see href="https://aka.ms/aspnet/analyzers"/>.</remarks>
    [DiagnosticRule]
    public static class ASP0006
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(ASP0006);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = AspNetCoreCategory.Usage;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://aka.ms/aspnet/analyzers";
    }

    /// <summary>Route parameter and argument optionality is mismatched.</summary>
    /// <remarks>See <see href="https://aka.ms/aspnet/analyzers"/>.</remarks>
    [DiagnosticRule]
    public static class ASP0007
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(ASP0007);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = AspNetCoreCategory.Usage;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://aka.ms/aspnet/analyzers";
    }

    /// <summary>Do not use ConfigureWebHost with WebApplicationBuilder.Host.</summary>
    /// <remarks>See <see href="https://aka.ms/aspnet/analyzers"/>.</remarks>
    [DiagnosticRule]
    public static class ASP0008
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(ASP0008);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = AspNetCoreCategory.Usage;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://aka.ms/aspnet/analyzers";
    }

    /// <summary>Do not use Configure with WebApplicationBuilder.WebHost.</summary>
    /// <remarks>See <see href="https://aka.ms/aspnet/analyzers"/>.</remarks>
    [DiagnosticRule]
    public static class ASP0009
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(ASP0009);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = AspNetCoreCategory.Usage;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://aka.ms/aspnet/analyzers";
    }

    /// <summary>Do not use UseStartup with WebApplicationBuilder.WebHost.</summary>
    /// <remarks>See <see href="https://aka.ms/aspnet/analyzers"/>.</remarks>
    [DiagnosticRule]
    public static class ASP0010
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(ASP0010);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = AspNetCoreCategory.Usage;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://aka.ms/aspnet/analyzers";
    }

    /// <summary>Suggest using builder.Logging over Host.ConfigureLogging or WebHost.ConfigureLogging.</summary>
    /// <remarks>See <see href="https://aka.ms/aspnet/analyzers"/>.</remarks>
    [DiagnosticRule]
    public static class ASP0011
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(ASP0011);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = AspNetCoreCategory.Usage;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://aka.ms/aspnet/analyzers";
    }

    /// <summary>Suggest using builder.Services over Host.ConfigureServices or WebHost.ConfigureServices.</summary>
    /// <remarks>See <see href="https://aka.ms/aspnet/analyzers"/>.</remarks>
    [DiagnosticRule]
    public static class ASP0012
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(ASP0012);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = AspNetCoreCategory.Usage;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://aka.ms/aspnet/analyzers";
    }

    /// <summary>Suggest switching from using Configure methods to WebApplicationBuilder.Configuration.</summary>
    /// <remarks>See <see href="https://aka.ms/aspnet/analyzers"/>.</remarks>
    [DiagnosticRule]
    public static class ASP0013
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(ASP0013);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = AspNetCoreCategory.Usage;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://aka.ms/aspnet/analyzers";
    }

    /// <summary>Suggest using top level route registrations.</summary>
    /// <remarks>See <see href="https://aka.ms/aspnet/analyzers"/>.</remarks>
    [DiagnosticRule]
    public static class ASP0014
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(ASP0014);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = AspNetCoreCategory.Usage;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://aka.ms/aspnet/analyzers";
    }

    /// <summary>Suggest using IHeaderDictionary properties.</summary>
    /// <remarks>See <see href="https://aka.ms/aspnet/analyzers"/>.</remarks>
    [DiagnosticRule]
    public static class ASP0015
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(ASP0015);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = AspNetCoreCategory.Usage;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://aka.ms/aspnet/analyzers";
    }

    /// <summary>Do not return a value from RequestDelegate.</summary>
    /// <remarks>See <see href="https://aka.ms/aspnet/analyzers"/>.</remarks>
    [DiagnosticRule]
    public static class ASP0016
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(ASP0016);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = AspNetCoreCategory.Usage;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://aka.ms/aspnet/analyzers";
    }

    /// <summary>Invalid route pattern.</summary>
    /// <remarks>See <see href="https://aka.ms/aspnet/analyzers"/>.</remarks>
    [DiagnosticRule]
    public static class ASP0017
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(ASP0017);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = AspNetCoreCategory.Usage;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://aka.ms/aspnet/analyzers";
    }

    /// <summary>Unused route parameter.</summary>
    /// <remarks>See <see href="https://aka.ms/aspnet/analyzers"/>.</remarks>
    [DiagnosticRule]
    public static class ASP0018
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(ASP0018);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = AspNetCoreCategory.Usage;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://aka.ms/aspnet/analyzers";
    }

    /// <summary>Suggest using IHeaderDictionary.Append or the indexer.</summary>
    /// <remarks>See <see href="https://aka.ms/aspnet/analyzers"/>.</remarks>
    [DiagnosticRule]
    public static class ASP0019
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(ASP0019);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = AspNetCoreCategory.Usage;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://aka.ms/aspnet/analyzers";
    }

    /// <summary>Complex types referenced by route parameters must be parsable.</summary>
    /// <remarks>See <see href="https://aka.ms/aspnet/analyzers"/>.</remarks>
    [DiagnosticRule]
    public static class ASP0020
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(ASP0020);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = AspNetCoreCategory.Usage;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://aka.ms/aspnet/analyzers";
    }

    /// <summary>When implementing BindAsync(...) method, the return type must be ValueTask&lt;T&gt;.</summary>
    /// <remarks>See <see href="https://aka.ms/aspnet/analyzers"/>.</remarks>
    [DiagnosticRule]
    public static class ASP0021
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(ASP0021);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = AspNetCoreCategory.Usage;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://aka.ms/aspnet/analyzers";
    }

    /// <summary>Route conflict detected between route handlers.</summary>
    /// <remarks>See <see href="https://aka.ms/aspnet/analyzers"/>.</remarks>
    [DiagnosticRule]
    public static class ASP0022
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(ASP0022);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = AspNetCoreCategory.Usage;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://aka.ms/aspnet/analyzers";
    }

    /// <summary>Route conflict detected between controller actions.</summary>
    /// <remarks>See <see href="https://aka.ms/aspnet/analyzers"/>.</remarks>
    [DiagnosticRule]
    public static class ASP0023
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(ASP0023);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = AspNetCoreCategory.Usage;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://aka.ms/aspnet/analyzers";
    }

    /// <summary>Route handler has multiple parameters with the [FromBody] attribute.</summary>
    /// <remarks>See <see href="https://aka.ms/aspnet/analyzers"/>.</remarks>
    [DiagnosticRule]
    public static class ASP0024
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(ASP0024);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = AspNetCoreCategory.Usage;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://aka.ms/aspnet/analyzers";
    }

    /// <summary>Use AddAuthorizationBuilder.</summary>
    /// <remarks>See <see href="https://aka.ms/aspnet/analyzers"/>.</remarks>
    [DiagnosticRule]
    public static class ASP0025
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(ASP0025);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = AspNetCoreCategory.Usage;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://aka.ms/aspnet/analyzers";
    }

    /// <summary>[Authorize] overridden by [AllowAnonymous] from farther away.</summary>
    /// <remarks>See <see href="https://aka.ms/aspnet/analyzers"/>.</remarks>
    [DiagnosticRule]
    public static class ASP0026
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(ASP0026);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = AspNetCoreCategory.Security;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://aka.ms/aspnet/analyzers";
    }

    /// <summary>Unnecessary public Program class declaration.</summary>
    /// <remarks>See <see href="https://aka.ms/aspnet/analyzers"/>.</remarks>
    [DiagnosticRule]
    public static class ASP0027
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(ASP0027);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = AspNetCoreCategory.Usage;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://aka.ms/aspnet/analyzers";
    }

    /// <summary>Consider using ListenAnyIP() instead of Listen(IPAddress.Any).</summary>
    /// <remarks>See <see href="https://aka.ms/aspnet/analyzers"/>.</remarks>
    [DiagnosticRule]
    public static class ASP0028
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(ASP0028);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = AspNetCoreCategory.Usage;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://aka.ms/aspnet/analyzers";
    }

    /// <summary>Component parameter should have public setters.</summary>
    [DiagnosticRule]
    public static class BL0001
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(BL0001);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = AspNetCoreCategory.Encapsulation;
    }

    /// <summary>Component has multiple CaptureUnmatchedValues parameters.</summary>
    [DiagnosticRule]
    public static class BL0002
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(BL0002);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = AspNetCoreCategory.Usage;
    }

    /// <summary>Component parameter with CaptureUnmatchedValues has the wrong type.</summary>
    [DiagnosticRule]
    public static class BL0003
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(BL0003);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = AspNetCoreCategory.Usage;
    }

    /// <summary>Component parameter should be public.</summary>
    [DiagnosticRule]
    public static class BL0004
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(BL0004);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = AspNetCoreCategory.Encapsulation;
    }

    /// <summary>Component parameter should not be set outside of its component.</summary>
    [DiagnosticRule]
    public static class BL0005
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(BL0005);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = AspNetCoreCategory.Usage;
    }

    /// <summary>Do not use RenderTree types.</summary>
    [DiagnosticRule]
    public static class BL0006
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(BL0006);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = AspNetCoreCategory.Usage;
    }

    /// <summary>Component parameters should be auto properties.</summary>
    [DiagnosticRule]
    public static class BL0007
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(BL0007);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = AspNetCoreCategory.Usage;
    }

    /// <summary>Property with [SupplyParameterFromForm] should not have initializer.</summary>
    [DiagnosticRule]
    public static class BL0008
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(BL0008);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = AspNetCoreCategory.Usage;
    }

    /// <summary>Property with [PersistentState] should not have initializer.</summary>
    [DiagnosticRule]
    public static class BL0009
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(BL0009);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = AspNetCoreCategory.Usage;
    }
}
