// <auto-generated>
//     Generated by eng/CatalogGen from the DiagnosticDescriptor instances declared by
//     Microsoft.CodeAnalysis.BannedApiAnalyzers 5.6.0 (language: cs).
//     Do not edit by hand: rerun the generator.
//
//     Only Id, Category, Title and HelpLinkUri are emitted, and only when the
//     descriptor actually supplies them. A rule's title is reproduced verbatim as its
//     documentation comment: it is the one sentence that says what the rule is about,
//     and it is Microsoft.CodeAnalysis.BannedApiAnalyzers's own wording. Rule descriptions and message
//     formats are the vendor's documentation and are not redistributed here.
// </auto-generated>

using DiagnosticCatalog;

[assembly: CatalogSource(
    source:        "Microsoft.CodeAnalysis.BannedApiAnalyzers",
    sourceVersion: "5.6.0",
    generatedOn:   "2026-08-05")]

namespace DiagnosticCatalog.BannedApi;

/// <summary>
/// The diagnostic categories used by Microsoft.CodeAnalysis.BannedApiAnalyzers, declared once each.
/// </summary>
/// <remarks>
/// INTERNAL by design. A category is reachable only through the rule that carries it:
/// write <c>SomeRule.Sxxxx.Category</c>, never the category constant directly. The two
/// spellings fold to the same string today and stop agreeing the day the vendor moves the
/// rule to another category -- the rule member follows, a category named on its own does
/// not, and the suppression is left asserting a category the rule no longer carries.
/// Nothing reports that: Roslyn ignores the category when it matches a suppression, so the
/// mistake has no symptom at all. Keeping this class out of the public surface makes that
/// decoupling unwritable rather than merely discouraged.
/// The public <c>Category</c> constant on each rule is initialised from here and folds to
/// the literal at compile time, so a consumer loses nothing.
/// </remarks>
[DiagnosticCategory]
internal static class BannedApiCategory
{
    /// <summary>The <c>ApiDesign</c> category.</summary>
    public const string ApiDesign = "ApiDesign";
}

/// <summary>
/// The Microsoft.CodeAnalysis.BannedApiAnalyzers diagnostic rules, as declared by that package's analyzers.
/// </summary>
public static class BannedApiRule
{
    /// <summary>Do not use banned APIs.</summary>
    /// <remarks>See <see href="https://github.com/dotnet/roslyn/blob/main/src/RoslynAnalyzers/Microsoft.CodeAnalysis.BannedApiAnalyzers/BannedApiAnalyzers.Help.md"/>.</remarks>
    [DiagnosticRule]
    public static class RS0030
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(RS0030);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = BannedApiCategory.ApiDesign;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/dotnet/roslyn/blob/main/src/RoslynAnalyzers/Microsoft.CodeAnalysis.BannedApiAnalyzers/BannedApiAnalyzers.Help.md";
    }

    /// <summary>The list of banned symbols contains a duplicate.</summary>
    /// <remarks>See <see href="https://github.com/dotnet/roslyn/blob/main/src/RoslynAnalyzers/Microsoft.CodeAnalysis.BannedApiAnalyzers/BannedApiAnalyzers.Help.md"/>.</remarks>
    [DiagnosticRule]
    public static class RS0031
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(RS0031);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = BannedApiCategory.ApiDesign;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/dotnet/roslyn/blob/main/src/RoslynAnalyzers/Microsoft.CodeAnalysis.BannedApiAnalyzers/BannedApiAnalyzers.Help.md";
    }

    /// <summary>External access to internal symbols outside the restricted namespace(s) is prohibited.</summary>
    [DiagnosticRule]
    public static class RS0035
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(RS0035);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = BannedApiCategory.ApiDesign;
    }
}
