// <auto-generated>
//     Generated by eng/CatalogGen from the DiagnosticDescriptor instances declared by
//     Microsoft.CodeAnalysis.CSharp.CodeStyle 5.6.0 (language: cs).
//     Do not edit by hand: rerun the generator.
//
//     Only Id, Category, Title and HelpLinkUri are emitted, and only when the
//     descriptor actually supplies them. A rule's title is reproduced verbatim as its
//     documentation comment: it is the one sentence that says what the rule is about,
//     and it is Microsoft.CodeAnalysis.CSharp.CodeStyle's own wording. Rule descriptions and message
//     formats are the vendor's documentation and are not redistributed here.
// </auto-generated>

using DiagnosticCatalog;

[assembly: CatalogSource(
    source:        "Microsoft.CodeAnalysis.CSharp.CodeStyle",
    sourceVersion: "5.6.0",
    generatedOn:   "2026-08-05")]

namespace DiagnosticCatalog.CodeStyle;

/// <summary>
/// The diagnostic categories used by Microsoft.CodeAnalysis.CSharp.CodeStyle, declared once each.
/// </summary>
/// <remarks>
/// INTERNAL by design. A category is reachable only through the rule that carries it:
/// write <c>SomeRule.Sxxxx.Category</c>, never the category constant directly. The two
/// spellings fold to the same string today and stop agreeing the day the vendor moves the
/// rule to another category -- the rule member follows, a category named on its own does
/// not, and the suppression is left asserting a category the rule no longer carries.
/// Nothing reports that: Roslyn ignores the category when it matches a suppression, so the
/// mistake has no symptom at all. Keeping this class out of the public surface makes that
/// decoupling unwritable rather than merely discouraged.
/// The public <c>Category</c> constant on each rule is initialised from here and folds to
/// the literal at compile time, so a consumer loses nothing.
/// </remarks>
[DiagnosticCategory]
internal static class CodeStyleCategory
{
    /// <summary>The <c>CodeQuality</c> category.</summary>
    public const string CodeQuality = "CodeQuality";

    /// <summary>The <c>Compiler</c> category.</summary>
    public const string Compiler = "Compiler";

    /// <summary>The <c>Style</c> category.</summary>
    public const string Style = "Style";
}

/// <summary>
/// The Microsoft.CodeAnalysis.CSharp.CodeStyle diagnostic rules, as declared by that package's analyzers.
/// </summary>
public static class CodeStyleRule
{
    /// <summary>Set MSBuild property 'GenerateDocumentationFile' to 'true'.</summary>
    /// <remarks>See <see href="https://github.com/dotnet/roslyn/issues/41640"/>.</remarks>
    [DiagnosticRule]
    public static class EnableGenerateDocumentationFile
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(EnableGenerateDocumentationFile);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = CodeStyleCategory.Style;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/dotnet/roslyn/issues/41640";
    }

    /// <summary>Remove Unnecessary Cast.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0004"/>.</remarks>
    [DiagnosticRule]
    public static class IDE0004
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IDE0004);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = CodeStyleCategory.Style;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0004";
    }

    /// <summary>Using directive is unnecessary.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0005"/>.</remarks>
    [DiagnosticRule]
    public static class IDE0005
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IDE0005);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = CodeStyleCategory.Style;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0005";
    }

    /// <summary>Using directive is unnecessary.</summary>
    [DiagnosticRule]
    public static class IDE0005_gen
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IDE0005_gen);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = CodeStyleCategory.Style;
    }

    /// <summary>Use implicit type.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0007"/>.</remarks>
    [DiagnosticRule]
    public static class IDE0007
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IDE0007);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = CodeStyleCategory.Style;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0007";
    }

    /// <summary>Use explicit type.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0008"/>.</remarks>
    [DiagnosticRule]
    public static class IDE0008
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IDE0008);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = CodeStyleCategory.Style;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0008";
    }

    /// <summary>Member access should be qualified.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0009"/>.</remarks>
    [DiagnosticRule]
    public static class IDE0009
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IDE0009);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = CodeStyleCategory.Style;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0009";
    }

    /// <summary>Add missing cases.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0010"/>.</remarks>
    [DiagnosticRule]
    public static class IDE0010
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IDE0010);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = CodeStyleCategory.Style;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0010";
    }

    /// <summary>Add braces.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0011"/>.</remarks>
    [DiagnosticRule]
    public static class IDE0011
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IDE0011);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = CodeStyleCategory.Style;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0011";
    }

    /// <summary>Use 'throw' expression.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0016"/>.</remarks>
    [DiagnosticRule]
    public static class IDE0016
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IDE0016);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = CodeStyleCategory.Style;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0016";
    }

    /// <summary>Simplify object initialization.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0017"/>.</remarks>
    [DiagnosticRule]
    public static class IDE0017
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IDE0017);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = CodeStyleCategory.Style;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0017";
    }

    /// <summary>Inline variable declaration.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0018"/>.</remarks>
    [DiagnosticRule]
    public static class IDE0018
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IDE0018);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = CodeStyleCategory.Style;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0018";
    }

    /// <summary>Use pattern matching.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0019"/>.</remarks>
    [DiagnosticRule]
    public static class IDE0019
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IDE0019);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = CodeStyleCategory.Style;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0019";
    }

    /// <summary>Use pattern matching.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0020"/>.</remarks>
    [DiagnosticRule]
    public static class IDE0020
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IDE0020);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = CodeStyleCategory.Style;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0020";
    }

    /// <summary>Use expression body for constructor.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0021"/>.</remarks>
    [DiagnosticRule]
    public static class IDE0021
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IDE0021);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = CodeStyleCategory.Style;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0021";
    }

    /// <summary>Use expression body for method.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0022"/>.</remarks>
    [DiagnosticRule]
    public static class IDE0022
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IDE0022);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = CodeStyleCategory.Style;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0022";
    }

    /// <summary>Use expression body for conversion operator.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0023"/>.</remarks>
    [DiagnosticRule]
    public static class IDE0023
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IDE0023);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = CodeStyleCategory.Style;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0023";
    }

    /// <summary>Use expression body for operator.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0024"/>.</remarks>
    [DiagnosticRule]
    public static class IDE0024
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IDE0024);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = CodeStyleCategory.Style;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0024";
    }

    /// <summary>Use expression body for property.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0025"/>.</remarks>
    [DiagnosticRule]
    public static class IDE0025
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IDE0025);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = CodeStyleCategory.Style;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0025";
    }

    /// <summary>Use expression body for indexer.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0026"/>.</remarks>
    [DiagnosticRule]
    public static class IDE0026
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IDE0026);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = CodeStyleCategory.Style;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0026";
    }

    /// <summary>Use expression body for accessor.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0027"/>.</remarks>
    [DiagnosticRule]
    public static class IDE0027
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IDE0027);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = CodeStyleCategory.Style;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0027";
    }

    /// <summary>Simplify collection initialization.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0028"/>.</remarks>
    [DiagnosticRule]
    public static class IDE0028
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IDE0028);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = CodeStyleCategory.Style;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0028";
    }

    /// <summary>Use coalesce expression.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0029"/>.</remarks>
    [DiagnosticRule]
    public static class IDE0029
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IDE0029);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = CodeStyleCategory.Style;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0029";
    }

    /// <summary>Use coalesce expression.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0030"/>.</remarks>
    [DiagnosticRule]
    public static class IDE0030
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IDE0030);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = CodeStyleCategory.Style;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0030";
    }

    /// <summary>Use null propagation.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0031"/>.</remarks>
    [DiagnosticRule]
    public static class IDE0031
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IDE0031);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = CodeStyleCategory.Style;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0031";
    }

    /// <summary>Use auto property.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0032"/>.</remarks>
    [DiagnosticRule]
    public static class IDE0032
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IDE0032);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = CodeStyleCategory.Style;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0032";
    }

    /// <summary>Use explicitly provided tuple name.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0033"/>.</remarks>
    [DiagnosticRule]
    public static class IDE0033
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IDE0033);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = CodeStyleCategory.Style;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0033";
    }

    /// <summary>Simplify 'default' expression.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0034"/>.</remarks>
    [DiagnosticRule]
    public static class IDE0034
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IDE0034);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = CodeStyleCategory.Style;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0034";
    }

    /// <summary>Unreachable code detected.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0035"/>.</remarks>
    [DiagnosticRule]
    public static class IDE0035
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IDE0035);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = CodeStyleCategory.Style;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0035";
    }

    /// <summary>Order modifiers.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0036"/>.</remarks>
    [DiagnosticRule]
    public static class IDE0036
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IDE0036);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = CodeStyleCategory.Style;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0036";
    }

    /// <summary>Use inferred member name.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0037"/>.</remarks>
    [DiagnosticRule]
    public static class IDE0037
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IDE0037);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = CodeStyleCategory.Style;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0037";
    }

    /// <summary>Use local function.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0039"/>.</remarks>
    [DiagnosticRule]
    public static class IDE0039
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IDE0039);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = CodeStyleCategory.Style;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0039";
    }

    /// <summary>Add accessibility modifiers.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0040"/>.</remarks>
    [DiagnosticRule]
    public static class IDE0040
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IDE0040);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = CodeStyleCategory.Style;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0040";
    }

    /// <summary>Use 'is null' check.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0041"/>.</remarks>
    [DiagnosticRule]
    public static class IDE0041
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IDE0041);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = CodeStyleCategory.Style;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0041";
    }

    /// <summary>Deconstruct variable declaration.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0042"/>.</remarks>
    [DiagnosticRule]
    public static class IDE0042
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IDE0042);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = CodeStyleCategory.Style;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0042";
    }

    /// <summary>Invalid format string.</summary>
    [DiagnosticRule]
    public static class IDE0043
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IDE0043);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = CodeStyleCategory.Compiler;
    }

    /// <summary>Add readonly modifier.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0044"/>.</remarks>
    [DiagnosticRule]
    public static class IDE0044
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IDE0044);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = CodeStyleCategory.Style;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0044";
    }

    /// <summary>Convert to conditional expression.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0045"/>.</remarks>
    [DiagnosticRule]
    public static class IDE0045
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IDE0045);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = CodeStyleCategory.Style;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0045";
    }

    /// <summary>Convert to conditional expression.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0046"/>.</remarks>
    [DiagnosticRule]
    public static class IDE0046
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IDE0046);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = CodeStyleCategory.Style;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0046";
    }

    /// <summary>Remove unnecessary parentheses.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0047"/>.</remarks>
    [DiagnosticRule]
    public static class IDE0047
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IDE0047);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = CodeStyleCategory.Style;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0047";
    }

    /// <summary>Add parentheses for clarity.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0048"/>.</remarks>
    [DiagnosticRule]
    public static class IDE0048
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IDE0048);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = CodeStyleCategory.Style;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0048";
    }

    /// <summary>Remove unused private members.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0051"/>.</remarks>
    [DiagnosticRule]
    public static class IDE0051
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IDE0051);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = CodeStyleCategory.Style;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0051";
    }

    /// <summary>Remove unread private members.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0052"/>.</remarks>
    [DiagnosticRule]
    public static class IDE0052
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IDE0052);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = CodeStyleCategory.Style;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0052";
    }

    /// <summary>Use block body for lambda expression.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0053"/>.</remarks>
    [DiagnosticRule]
    public static class IDE0053
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IDE0053);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = CodeStyleCategory.Style;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0053";
    }

    /// <summary>Use compound assignment.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0054"/>.</remarks>
    [DiagnosticRule]
    public static class IDE0054
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IDE0054);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = CodeStyleCategory.Style;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0054";
    }

    /// <summary>Fix formatting.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0055"/>.</remarks>
    [DiagnosticRule]
    public static class IDE0055
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IDE0055);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = CodeStyleCategory.Style;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0055";
    }

    /// <summary>Use index operator.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0056"/>.</remarks>
    [DiagnosticRule]
    public static class IDE0056
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IDE0056);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = CodeStyleCategory.Style;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0056";
    }

    /// <summary>Use range operator.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0057"/>.</remarks>
    [DiagnosticRule]
    public static class IDE0057
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IDE0057);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = CodeStyleCategory.Style;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0057";
    }

    /// <summary>Expression value is never used.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0058"/>.</remarks>
    [DiagnosticRule]
    public static class IDE0058
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IDE0058);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = CodeStyleCategory.Style;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0058";
    }

    /// <summary>Unnecessary assignment of a value.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0059"/>.</remarks>
    [DiagnosticRule]
    public static class IDE0059
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IDE0059);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = CodeStyleCategory.Style;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0059";
    }

    /// <summary>Remove unused parameter.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0060"/>.</remarks>
    [DiagnosticRule]
    public static class IDE0060
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IDE0060);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = CodeStyleCategory.Style;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0060";
    }

    /// <summary>Use expression body for local function.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0061"/>.</remarks>
    [DiagnosticRule]
    public static class IDE0061
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IDE0061);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = CodeStyleCategory.Style;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0061";
    }

    /// <summary>Make local function 'static'.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0062"/>.</remarks>
    [DiagnosticRule]
    public static class IDE0062
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IDE0062);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = CodeStyleCategory.Style;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0062";
    }

    /// <summary>Use simple 'using' statement.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0063"/>.</remarks>
    [DiagnosticRule]
    public static class IDE0063
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IDE0063);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = CodeStyleCategory.Style;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0063";
    }

    /// <summary>Make readonly fields writable.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0064"/>.</remarks>
    [DiagnosticRule]
    public static class IDE0064
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IDE0064);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = CodeStyleCategory.CodeQuality;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0064";
    }

    /// <summary>Misplaced using directive.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0065"/>.</remarks>
    [DiagnosticRule]
    public static class IDE0065
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IDE0065);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = CodeStyleCategory.Style;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0065";
    }

    /// <summary>Convert switch statement to expression.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0066"/>.</remarks>
    [DiagnosticRule]
    public static class IDE0066
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IDE0066);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = CodeStyleCategory.Style;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0066";
    }

    /// <summary>Use 'System.HashCode'.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0070"/>.</remarks>
    [DiagnosticRule]
    public static class IDE0070
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IDE0070);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = CodeStyleCategory.Style;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0070";
    }

    /// <summary>Simplify interpolation.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0071"/>.</remarks>
    [DiagnosticRule]
    public static class IDE0071
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IDE0071);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = CodeStyleCategory.Style;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0071";
    }

    /// <summary>Add missing cases.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0072"/>.</remarks>
    [DiagnosticRule]
    public static class IDE0072
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IDE0072);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = CodeStyleCategory.Style;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0072";
    }

    /// <summary>The file header is missing or not located at the top of the file.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0073"/>.</remarks>
    [DiagnosticRule]
    public static class IDE0073
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IDE0073);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = CodeStyleCategory.Style;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0073";
    }

    /// <summary>Use compound assignment.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0074"/>.</remarks>
    [DiagnosticRule]
    public static class IDE0074
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IDE0074);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = CodeStyleCategory.Style;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0074";
    }

    /// <summary>Simplify conditional expression.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0075"/>.</remarks>
    [DiagnosticRule]
    public static class IDE0075
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IDE0075);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = CodeStyleCategory.Style;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0075";
    }

    /// <summary>Invalid global 'SuppressMessageAttribute'.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0076"/>.</remarks>
    [DiagnosticRule]
    public static class IDE0076
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IDE0076);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = CodeStyleCategory.CodeQuality;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0076";
    }

    /// <summary>Avoid legacy format target in 'SuppressMessageAttribute'.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0077"/>.</remarks>
    [DiagnosticRule]
    public static class IDE0077
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IDE0077);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = CodeStyleCategory.CodeQuality;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0077";
    }

    /// <summary>Use pattern matching.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0078"/>.</remarks>
    [DiagnosticRule]
    public static class IDE0078
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IDE0078);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = CodeStyleCategory.Style;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0078";
    }

    /// <summary>Remove unnecessary suppression operator.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0080"/>.</remarks>
    [DiagnosticRule]
    public static class IDE0080
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IDE0080);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = CodeStyleCategory.Style;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0080";
    }

    /// <summary>'typeof' can be converted to 'nameof'.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0082"/>.</remarks>
    [DiagnosticRule]
    public static class IDE0082
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IDE0082);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = CodeStyleCategory.Style;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0082";
    }

    /// <summary>Use pattern matching.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0083"/>.</remarks>
    [DiagnosticRule]
    public static class IDE0083
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IDE0083);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = CodeStyleCategory.Style;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0083";
    }

    /// <summary>Use 'new(...)'.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0090"/>.</remarks>
    [DiagnosticRule]
    public static class IDE0090
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IDE0090);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = CodeStyleCategory.Style;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0090";
    }

    /// <summary>Remove redundant equality.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0100"/>.</remarks>
    [DiagnosticRule]
    public static class IDE0100
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IDE0100);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = CodeStyleCategory.Style;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0100";
    }

    /// <summary>Remove unnecessary discard.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0110"/>.</remarks>
    [DiagnosticRule]
    public static class IDE0110
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IDE0110);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = CodeStyleCategory.Style;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0110";
    }

    /// <summary>Simplify LINQ expression.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0120"/>.</remarks>
    [DiagnosticRule]
    public static class IDE0120
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IDE0120);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = CodeStyleCategory.Style;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0120";
    }

    /// <summary>Simplify LINQ expression.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0121"/>.</remarks>
    [DiagnosticRule]
    public static class IDE0121
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IDE0121);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = CodeStyleCategory.Style;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0121";
    }

    /// <summary>Namespace does not match folder structure.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0130"/>.</remarks>
    [DiagnosticRule]
    public static class IDE0130
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IDE0130);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = CodeStyleCategory.Style;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0130";
    }

    /// <summary>Prefer 'null' check over type check.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0150"/>.</remarks>
    [DiagnosticRule]
    public static class IDE0150
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IDE0150);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = CodeStyleCategory.Style;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0150";
    }

    /// <summary>Convert to block scoped namespace.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0160"/>.</remarks>
    [DiagnosticRule]
    public static class IDE0160
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IDE0160);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = CodeStyleCategory.Style;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0160";
    }

    /// <summary>Convert to file-scoped namespace.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0161"/>.</remarks>
    [DiagnosticRule]
    public static class IDE0161
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IDE0161);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = CodeStyleCategory.Style;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0161";
    }

    /// <summary>Property pattern can be simplified.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0170"/>.</remarks>
    [DiagnosticRule]
    public static class IDE0170
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IDE0170);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = CodeStyleCategory.Style;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0170";
    }

    /// <summary>Use tuple to swap values.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0180"/>.</remarks>
    [DiagnosticRule]
    public static class IDE0180
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IDE0180);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = CodeStyleCategory.Style;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0180";
    }

    /// <summary>Remove unnecessary lambda expression.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0200"/>.</remarks>
    [DiagnosticRule]
    public static class IDE0200
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IDE0200);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = CodeStyleCategory.Style;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0200";
    }

    /// <summary>Convert to top-level statements.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0210"/>.</remarks>
    [DiagnosticRule]
    public static class IDE0210
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IDE0210);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = CodeStyleCategory.Style;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0210";
    }

    /// <summary>Convert to 'Program.Main' style program.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0211"/>.</remarks>
    [DiagnosticRule]
    public static class IDE0211
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IDE0211);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = CodeStyleCategory.Style;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0211";
    }

    /// <summary>Add explicit cast.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0220"/>.</remarks>
    [DiagnosticRule]
    public static class IDE0220
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IDE0220);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = CodeStyleCategory.Style;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0220";
    }

    /// <summary>Add explicit cast.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0221"/>.</remarks>
    [DiagnosticRule]
    public static class IDE0221
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IDE0221);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = CodeStyleCategory.Style;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0221";
    }

    /// <summary>Use UTF-8 string literal.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0230"/>.</remarks>
    [DiagnosticRule]
    public static class IDE0230
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IDE0230);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = CodeStyleCategory.Style;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0230";
    }

    /// <summary>Remove redundant nullable directive.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0240"/>.</remarks>
    [DiagnosticRule]
    public static class IDE0240
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IDE0240);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = CodeStyleCategory.Style;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0240";
    }

    /// <summary>Remove unnecessary nullable directive.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0241"/>.</remarks>
    [DiagnosticRule]
    public static class IDE0241
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IDE0241);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = CodeStyleCategory.Style;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0241";
    }

    /// <summary>Make struct 'readonly'.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0250"/>.</remarks>
    [DiagnosticRule]
    public static class IDE0250
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IDE0250);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = CodeStyleCategory.Style;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0250";
    }

    /// <summary>Make member 'readonly'.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0251"/>.</remarks>
    [DiagnosticRule]
    public static class IDE0251
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IDE0251);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = CodeStyleCategory.Style;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0251";
    }

    /// <summary>Use pattern matching.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0260"/>.</remarks>
    [DiagnosticRule]
    public static class IDE0260
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IDE0260);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = CodeStyleCategory.Style;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0260";
    }

    /// <summary>Use coalesce expression.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0270"/>.</remarks>
    [DiagnosticRule]
    public static class IDE0270
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IDE0270);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = CodeStyleCategory.Style;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0270";
    }

    /// <summary>Use 'nameof'.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0280"/>.</remarks>
    [DiagnosticRule]
    public static class IDE0280
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IDE0280);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = CodeStyleCategory.Style;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0280";
    }

    /// <summary>Use primary constructor.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0290"/>.</remarks>
    [DiagnosticRule]
    public static class IDE0290
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IDE0290);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = CodeStyleCategory.Style;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0290";
    }

    /// <summary>Simplify collection initialization.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0300"/>.</remarks>
    [DiagnosticRule]
    public static class IDE0300
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IDE0300);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = CodeStyleCategory.Style;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0300";
    }

    /// <summary>Simplify collection initialization.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0301"/>.</remarks>
    [DiagnosticRule]
    public static class IDE0301
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IDE0301);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = CodeStyleCategory.Style;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0301";
    }

    /// <summary>Simplify collection initialization.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0302"/>.</remarks>
    [DiagnosticRule]
    public static class IDE0302
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IDE0302);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = CodeStyleCategory.Style;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0302";
    }

    /// <summary>Simplify collection initialization.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0303"/>.</remarks>
    [DiagnosticRule]
    public static class IDE0303
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IDE0303);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = CodeStyleCategory.Style;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0303";
    }

    /// <summary>Simplify collection initialization.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0304"/>.</remarks>
    [DiagnosticRule]
    public static class IDE0304
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IDE0304);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = CodeStyleCategory.Style;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0304";
    }

    /// <summary>Simplify collection initialization.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0305"/>.</remarks>
    [DiagnosticRule]
    public static class IDE0305
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IDE0305);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = CodeStyleCategory.Style;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0305";
    }

    /// <summary>Simplify collection initialization.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0306"/>.</remarks>
    [DiagnosticRule]
    public static class IDE0306
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IDE0306);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = CodeStyleCategory.Style;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0306";
    }

    /// <summary>Make anonymous function static.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0320"/>.</remarks>
    [DiagnosticRule]
    public static class IDE0320
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IDE0320);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = CodeStyleCategory.Style;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0320";
    }

    /// <summary>Use 'System.Threading.Lock'.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0330"/>.</remarks>
    [DiagnosticRule]
    public static class IDE0330
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IDE0330);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = CodeStyleCategory.Style;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0330";
    }

    /// <summary>Use unbound generic type.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0340"/>.</remarks>
    [DiagnosticRule]
    public static class IDE0340
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IDE0340);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = CodeStyleCategory.Style;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0340";
    }

    /// <summary>Use implicitly typed lambda.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0350"/>.</remarks>
    [DiagnosticRule]
    public static class IDE0350
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IDE0350);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = CodeStyleCategory.Style;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0350";
    }

    /// <summary>Simplify property accessor.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0360"/>.</remarks>
    [DiagnosticRule]
    public static class IDE0360
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IDE0360);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = CodeStyleCategory.Style;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0360";
    }

    /// <summary>Remove unnecessary suppression.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0370"/>.</remarks>
    [DiagnosticRule]
    public static class IDE0370
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IDE0370);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = CodeStyleCategory.Style;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0370";
    }

    /// <summary>Remove unnecessary 'unsafe' modifier.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0380"/>.</remarks>
    [DiagnosticRule]
    public static class IDE0380
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IDE0380);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = CodeStyleCategory.Style;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0380";
    }

    /// <summary>Make method synchronous.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0390"/>.</remarks>
    [DiagnosticRule]
    public static class IDE0390
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IDE0390);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = CodeStyleCategory.Style;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0390";
    }

    /// <summary>Make method synchronous.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0391"/>.</remarks>
    [DiagnosticRule]
    public static class IDE0391
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IDE0391);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = CodeStyleCategory.Style;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0391";
    }

    /// <summary>Delegate invocation can be simplified.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide1005"/>.</remarks>
    [DiagnosticRule]
    public static class IDE1005
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IDE1005);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = CodeStyleCategory.Style;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide1005";
    }

    /// <summary>Naming Styles.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide1006"/>.</remarks>
    [DiagnosticRule]
    public static class IDE1006
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IDE1006);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = CodeStyleCategory.Style;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide1006";
    }

    /// <summary>Avoid multiple blank lines.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide2000"/>.</remarks>
    [DiagnosticRule]
    public static class IDE2000
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IDE2000);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = CodeStyleCategory.Style;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide2000";
    }

    /// <summary>Embedded statements must be on their own line.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide2001"/>.</remarks>
    [DiagnosticRule]
    public static class IDE2001
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IDE2001);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = CodeStyleCategory.Style;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide2001";
    }

    /// <summary>Consecutive braces must not have blank line between them.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide2002"/>.</remarks>
    [DiagnosticRule]
    public static class IDE2002
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IDE2002);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = CodeStyleCategory.Style;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide2002";
    }

    /// <summary>Blank line required between block and subsequent statement.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide2003"/>.</remarks>
    [DiagnosticRule]
    public static class IDE2003
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IDE2003);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = CodeStyleCategory.Style;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide2003";
    }

    /// <summary>Blank line not allowed after constructor initializer colon.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide2004"/>.</remarks>
    [DiagnosticRule]
    public static class IDE2004
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IDE2004);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = CodeStyleCategory.Style;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide2004";
    }

    /// <summary>Blank line not allowed after conditional expression token.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide2005"/>.</remarks>
    [DiagnosticRule]
    public static class IDE2005
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IDE2005);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = CodeStyleCategory.Style;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide2005";
    }

    /// <summary>Blank line not allowed after arrow expression clause token.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide2006"/>.</remarks>
    [DiagnosticRule]
    public static class IDE2006
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IDE2006);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = CodeStyleCategory.Style;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide2006";
    }

    /// <summary>Rule <c>RemoveUnnecessaryImportsFixable</c>, category <c>Style</c>.</summary>
    [DiagnosticRule]
    public static class RemoveUnnecessaryImportsFixable
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(RemoveUnnecessaryImportsFixable);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = CodeStyleCategory.Style;
    }
}
