using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text.RegularExpressions;
using Xunit;

namespace DiagnosticCatalog.Catalogs.UnitTests;

/// <summary>
/// Invariants of the generated <em>source</em> rather than of the compiled result.
/// <para>
/// These exist because constant folding hides the distinction that matters here. A rule reaching
/// its category through the shared constant and a rule repeating the literal compile to
/// byte-identical metadata, so no amount of reflection can tell them apart — the check has to read
/// what the generator wrote. The files are copied beside the test binary by the project file.
/// </para>
/// </summary>
public sealed class GeneratedCatalogSourceTests
{
    public static TheoryData<string> CatalogSources() =>
    [
        "SonarRules.g.cs",
        "NetAnalyzersRules.g.cs",
        "StyleCopRules.g.cs",
    ];

    /// <summary>
    /// Line endings are normalised to LF because none of these checks is about them, and every one
    /// of them anchors on <c>$</c> under <see cref="RegexOptions.Multiline"/> — which matches before
    /// a line feed, not before a carriage return. The repository leaves line-ending handling to git
    /// outside a narrow snapshot rule (see <c>.gitattributes</c>), so these files check out CRLF on
    /// Windows, and an un-normalised read makes the emptiness assertions below pass vacuously there:
    /// green on a violation they exist to catch. <c>ReplaceLineEndings</c> would say this better but
    /// does not exist on .NET Framework, where the floor runs.
    /// </summary>
    private static string Read(string fileName)
    {
        string path = Path.Combine(AppContext.BaseDirectory, "catalogs", fileName);
        Assert.True(File.Exists(path), $"Generated source not found beside the tests: {path}");
        return File.ReadAllText(path).Replace("\r\n", "\n");
    }

    /// <summary>
    /// Every rule reaches its category through the catalog's category class. Repeating the literal
    /// would work identically at run time and would reintroduce exactly what the indirection
    /// removes: one value spread over hundreds of declarations — 456 of them for 13 distinct
    /// categories in the Sonar catalog — each free to drift on the next regeneration.
    /// </summary>
    [Theory]
    [MemberData(nameof(CatalogSources))]
    public void No_rule_repeats_a_category_literal(string fileName)
    {
        string source = Read(fileName);

        // Rule members sit at eight spaces; the category class declares its own at four.
        // Cast: MatchCollection is only non-generic on .NET Framework, where the floor runs.
        List<string> literals = Regex
            .Matches(source, @"^        public const string Category = ""[^""]*"";$", RegexOptions.Multiline)
            .Cast<Match>()
            .Select(m => m.Value.Trim())
            .ToList();

        Assert.Empty(literals);
    }

    [Theory]
    [MemberData(nameof(CatalogSources))]
    public void Every_rule_category_names_a_constant_of_the_category_class(string fileName)
    {
        string source = Read(fileName);

        MatchCollection references = Regex.Matches(
            source, @"^        public const string Category = (\w+)\.(\w+);$", RegexOptions.Multiline);
        Assert.NotEmpty(references);

        // ToHashSet does not exist on .NET Framework; the constructor overload does.
        HashSet<string> declared = new(
            Regex.Matches(source, @"^    public const string (\w+) = ""[^""]*"";$", RegexOptions.Multiline)
                .Cast<Match>()
                .Select(m => m.Groups[1].Value),
            StringComparer.Ordinal);

        foreach (Match reference in references.Cast<Match>())
        {
            Assert.Contains(reference.Groups[2].Value, declared);
        }
    }

    /// <summary>
    /// The file states which upstream release it mirrors and marks itself generated, so nobody
    /// edits it by hand and loses the change on the next regeneration.
    /// </summary>
    [Theory]
    [MemberData(nameof(CatalogSources))]
    public void The_generated_file_declares_its_provenance(string fileName)
    {
        string source = Read(fileName);

        Assert.Contains("<auto-generated>", source, StringComparison.Ordinal);
        Assert.Contains("Do not edit by hand", source, StringComparison.Ordinal);
        Assert.Matches(@"\[assembly: CatalogSource\(", source);
    }

    /// <summary>
    /// Rule titles and descriptions are the upstream vendor's authored content. The generator emits
    /// identifiers, categories and help links — facts about the software — and nothing else, so a
    /// regeneration that started copying the prose would be a licensing change, not a data update.
    /// </summary>
    [Theory]
    [MemberData(nameof(CatalogSources))]
    public void No_vendor_prose_is_redistributed(string fileName)
    {
        string source = Read(fileName);

        foreach (string member in new[] { "Title", "Description", "MessageFormat" })
        {
            Assert.DoesNotMatch($@"public const string {member} =", source);
        }
    }
}
