// <auto-generated>
//     Generated by eng/CatalogGen from the DiagnosticDescriptor instances declared by
//     Microsoft.NET.ILLink.Tasks 10.0.10 (language: cs).
//     Do not edit by hand: rerun the generator.
//
//     Only Id, Category, Title and HelpLinkUri are emitted, and only when the
//     descriptor actually supplies them. A rule's title is reproduced verbatim as its
//     documentation comment: it is the one sentence that says what the rule is about,
//     and it is Microsoft.NET.ILLink.Tasks's own wording. Rule descriptions and message
//     formats are the vendor's documentation and are not redistributed here.
// </auto-generated>

using DiagnosticCatalog;

[assembly: CatalogSource(
    source:        "Microsoft.NET.ILLink.Tasks",
    sourceVersion: "10.0.10",
    generatedOn:   "2026-08-05")]

namespace DiagnosticCatalog.Trimming;

/// <summary>
/// The diagnostic categories used by Microsoft.NET.ILLink.Tasks, declared once each.
/// </summary>
/// <remarks>
/// INTERNAL by design. A category is reachable only through the rule that carries it:
/// write <c>SomeRule.Sxxxx.Category</c>, never the category constant directly. The two
/// spellings fold to the same string today and stop agreeing the day the vendor moves the
/// rule to another category -- the rule member follows, a category named on its own does
/// not, and the suppression is left asserting a category the rule no longer carries.
/// Nothing reports that: Roslyn ignores the category when it matches a suppression, so the
/// mistake has no symptom at all. Keeping this class out of the public surface makes that
/// decoupling unwritable rather than merely discouraged.
/// The public <c>Category</c> constant on each rule is initialised from here and folds to
/// the literal at compile time, so a consumer loses nothing.
/// </remarks>
[DiagnosticCategory]
internal static class TrimCategory
{
    /// <summary>The <c>AOT</c> category.</summary>
    public const string AOT = "AOT";

    /// <summary>The <c>SingleFile</c> category.</summary>
    public const string SingleFile = "SingleFile";

    /// <summary>The <c>Trimming</c> category.</summary>
    public const string Trimming = "Trimming";
}

/// <summary>
/// The Microsoft.NET.ILLink.Tasks diagnostic rules, as declared by that package's analyzers.
/// </summary>
public static class TrimRule
{
    /// <summary>Members annotated with 'RequiresUnreferencedCodeAttribute' require dynamic access otherwise can break functionality when trimming application code.</summary>
    [DiagnosticRule]
    public static class IL2026
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IL2026);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = TrimCategory.Trimming;
    }

    /// <summary>The value passed as the assembly name or type name to the CreateInstance method can't be statically analyzed.</summary>
    [DiagnosticRule]
    public static class IL2032
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IL2032);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = TrimCategory.Trimming;
    }

    /// <summary>The 'DynamicallyAccessedMembersAttribute' is not allowed on methods. It is allowed on method return value or method parameters.</summary>
    [DiagnosticRule]
    public static class IL2041
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IL2041);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = TrimCategory.Trimming;
    }

    /// <summary>'DynamicallyAccessedMembersAttribute' on property conflicts with the same attribute on its accessor.</summary>
    [DiagnosticRule]
    public static class IL2043
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IL2043);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = TrimCategory.Trimming;
    }

    /// <summary>'RequiresUnreferencedCodeAttribute' annotations must match across all interface implementations or overrides.</summary>
    [DiagnosticRule]
    public static class IL2046
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IL2046);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = TrimCategory.Trimming;
    }

    /// <summary>Correctness of COM interop cannot be guaranteed after trimming. Interfaces and interface members might be removed.</summary>
    [DiagnosticRule]
    public static class IL2050
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IL2050);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = TrimCategory.Trimming;
    }

    /// <summary>Either the type on which the MakeGenericType is called can't be statically determined, or the type parameters to be used for generic arguments can't be statically determined.</summary>
    [DiagnosticRule]
    public static class IL2055
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IL2055);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = TrimCategory.Trimming;
    }

    /// <summary>Unrecognized value passed to the parameter of method. It's not possible to guarantee the availability of the target type.</summary>
    [DiagnosticRule]
    public static class IL2057
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IL2057);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = TrimCategory.Trimming;
    }

    /// <summary>Parameters passed to method cannot be analyzed. Consider using methods 'System.Type.GetType' and `System.Activator.CreateInstance` instead.</summary>
    [DiagnosticRule]
    public static class IL2058
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IL2058);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = TrimCategory.Trimming;
    }

    /// <summary>The type passed to the RunClassConstructor is not statically known, Trimmer can't make sure that its static constructor is available.</summary>
    [DiagnosticRule]
    public static class IL2059
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IL2059);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = TrimCategory.Trimming;
    }

    /// <summary>Call to 'System.Reflection.MethodInfo.MakeGenericMethod' can not be statically analyzed. It's not possible to guarantee the availability of requirements of the generic method.</summary>
    [DiagnosticRule]
    public static class IL2060
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IL2060);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = TrimCategory.Trimming;
    }

    /// <summary>The parameter of method has a DynamicallyAccessedMembersAttribute, but the value passed to it can not be statically analyzed.</summary>
    [DiagnosticRule]
    public static class IL2062
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IL2062);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = TrimCategory.Trimming;
    }

    /// <summary>The return value of method has a DynamicallyAccessedMembersAttribute, but the value returned from the method can not be statically analyzed.</summary>
    [DiagnosticRule]
    public static class IL2063
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IL2063);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = TrimCategory.Trimming;
    }

    /// <summary>The field has a DynamicallyAccessedMembersAttribute, but the value assigned to it can not be statically analyzed.</summary>
    [DiagnosticRule]
    public static class IL2064
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IL2064);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = TrimCategory.Trimming;
    }

    /// <summary>The method has a DynamicallyAccessedMembersAttribute (which applies to the implicit 'this' parameter), but the value used for the 'this' parameter can not be statically analyzed.</summary>
    [DiagnosticRule]
    public static class IL2065
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IL2065);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = TrimCategory.Trimming;
    }

    /// <summary>The generic parameter of type or method has a DynamicallyAccessedMembersAttribute, but the value used for it can not be statically analyzed.</summary>
    [DiagnosticRule]
    public static class IL2066
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IL2066);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = TrimCategory.Trimming;
    }

    /// <summary>Target parameter argument does not satisfy 'DynamicallyAccessedMembersAttribute' in call to target method. The parameter of method does not have matching annotations.</summary>
    [DiagnosticRule]
    public static class IL2067
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IL2067);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = TrimCategory.Trimming;
    }

    /// <summary>Target method return value does not satisfy 'DynamicallyAccessedMembersAttribute' requirements. The parameter of method does not have matching annotations.</summary>
    [DiagnosticRule]
    public static class IL2068
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IL2068);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = TrimCategory.Trimming;
    }

    /// <summary>Value stored in field does not satisfy 'DynamicallyAccessedMembersAttribute' requirements. The parameter of method does not have matching annotations.</summary>
    [DiagnosticRule]
    public static class IL2069
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IL2069);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = TrimCategory.Trimming;
    }

    /// <summary>'this' argument does not satisfy 'DynamicallyAccessedMembersAttribute' in call to target method. The parameter of method does not have matching annotations.</summary>
    [DiagnosticRule]
    public static class IL2070
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IL2070);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = TrimCategory.Trimming;
    }

    /// <summary>Generic argument does not satisfy 'DynamicallyAccessedMembersAttribute' in target method or type. The parameter of method does not have matching annotations.</summary>
    [DiagnosticRule]
    public static class IL2071
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IL2071);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = TrimCategory.Trimming;
    }

    /// <summary>Target parameter argument does not satisfy 'DynamicallyAccessedMembersAttribute' in call to target method. The return value of the source method does not have matching annotations.</summary>
    [DiagnosticRule]
    public static class IL2072
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IL2072);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = TrimCategory.Trimming;
    }

    /// <summary>Target method return value does not satisfy 'DynamicallyAccessedMembersAttribute' requirements. The return value of the source method does not have matching annotations.</summary>
    [DiagnosticRule]
    public static class IL2073
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IL2073);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = TrimCategory.Trimming;
    }

    /// <summary>Value stored in field does not satisfy 'DynamicallyAccessedMembersAttribute' requirements. The return value of the source method does not have matching annotations.</summary>
    [DiagnosticRule]
    public static class IL2074
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IL2074);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = TrimCategory.Trimming;
    }

    /// <summary>'this' argument does not satisfy 'DynamicallyAccessedMembersAttribute' in call to target method. The return value of the source method does not have matching annotations.</summary>
    [DiagnosticRule]
    public static class IL2075
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IL2075);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = TrimCategory.Trimming;
    }

    /// <summary>Target generic argument does not satisfy 'DynamicallyAccessedMembersAttribute' in target method or type. The return value of the source method does not have matching annotations. The source value must declare at least the same requirements as those declared on the target location it is assigned to.</summary>
    [DiagnosticRule]
    public static class IL2076
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IL2076);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = TrimCategory.Trimming;
    }

    /// <summary>Target parameter argument does not satisfy 'DynamicallyAccessedMembersAttribute' in call to target method. The source field does not have matching annotations.</summary>
    [DiagnosticRule]
    public static class IL2077
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IL2077);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = TrimCategory.Trimming;
    }

    /// <summary>Target method return value does not satisfy 'DynamicallyAccessedMembersAttribute' requirements. The source field does not have matching annotations.</summary>
    [DiagnosticRule]
    public static class IL2078
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IL2078);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = TrimCategory.Trimming;
    }

    /// <summary>Value stored in target field does not satisfy 'DynamicallyAccessedMembersAttribute' requirements. The source field does not have matching annotations.</summary>
    [DiagnosticRule]
    public static class IL2079
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IL2079);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = TrimCategory.Trimming;
    }

    /// <summary>'this' argument does not satisfy 'DynamicallyAccessedMembersAttribute' in call to target method. The source field does not have matching annotations.</summary>
    [DiagnosticRule]
    public static class IL2080
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IL2080);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = TrimCategory.Trimming;
    }

    /// <summary>Target generic argument does not satisfy 'DynamicallyAccessedMembersAttribute' in target method or type. The source field does not have matching annotations.</summary>
    [DiagnosticRule]
    public static class IL2081
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IL2081);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = TrimCategory.Trimming;
    }

    /// <summary>Target parameter argument does not satisfy 'DynamicallyAccessedMembersAttribute' in call to target method. The implicit 'this' argument of source method does not have matching annotations.</summary>
    [DiagnosticRule]
    public static class IL2082
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IL2082);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = TrimCategory.Trimming;
    }

    /// <summary>Target method return value does not satisfy 'DynamicallyAccessedMembersAttribute' requirements. The implicit 'this' argument of source method does not have matching annotations.</summary>
    [DiagnosticRule]
    public static class IL2083
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IL2083);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = TrimCategory.Trimming;
    }

    /// <summary>Value stored in target field does not satisfy 'DynamicallyAccessedMembersAttribute' requirements. The implicit 'this' argument of source method does not have matching annotations.</summary>
    [DiagnosticRule]
    public static class IL2084
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IL2084);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = TrimCategory.Trimming;
    }

    /// <summary>'this' argument does not satisfy 'DynamicallyAccessedMembersAttribute' in call to target method. The implicit 'this' argument of source method does not have matching annotations.</summary>
    [DiagnosticRule]
    public static class IL2085
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IL2085);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = TrimCategory.Trimming;
    }

    /// <summary>Target generic argument does not satisfy 'DynamicallyAccessedMembersAttribute' in target method or type. The implicit 'this' argument of source method does not have matching annotations.</summary>
    [DiagnosticRule]
    public static class IL2086
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IL2086);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = TrimCategory.Trimming;
    }

    /// <summary>Target parameter argument does not satisfy 'DynamicallyAccessedMembersAttribute' in call to target method. The generic parameter of the source method or type does not have matching annotations.</summary>
    [DiagnosticRule]
    public static class IL2087
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IL2087);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = TrimCategory.Trimming;
    }

    /// <summary>Target method return value does not satisfy 'DynamicallyAccessedMembersAttribute' requirements. The generic parameter of the source method or type does not have matching annotations.</summary>
    [DiagnosticRule]
    public static class IL2088
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IL2088);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = TrimCategory.Trimming;
    }

    /// <summary>Value stored in target field does not satisfy 'DynamicallyAccessedMembersAttribute' requirements. The generic parameter of the source method or type does not have matching annotations.</summary>
    [DiagnosticRule]
    public static class IL2089
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IL2089);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = TrimCategory.Trimming;
    }

    /// <summary>'this' argument does not satisfy 'DynamicallyAccessedMembersAttribute' in call to target method. The generic parameter of the source method or type does not have matching annotations.</summary>
    [DiagnosticRule]
    public static class IL2090
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IL2090);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = TrimCategory.Trimming;
    }

    /// <summary>Target generic argument does not satisfy 'DynamicallyAccessedMembersAttribute' in target method or type. The generic parameter of the source method or type does not have matching annotations.</summary>
    [DiagnosticRule]
    public static class IL2091
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IL2091);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = TrimCategory.Trimming;
    }

    /// <summary>'DynamicallyAccessedMemberTypes' on the parameter of method don't match overridden parameter of method. All overridden members must have the same 'DynamicallyAccessedMembersAttribute' usage.</summary>
    [DiagnosticRule]
    public static class IL2092
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IL2092);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = TrimCategory.Trimming;
    }

    /// <summary>'DynamicallyAccessedMemberTypes' on the return value of method don't match overridden return value of method. All overridden members must have the same 'DynamicallyAccessedMembersAttribute' usage.</summary>
    [DiagnosticRule]
    public static class IL2093
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IL2093);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = TrimCategory.Trimming;
    }

    /// <summary>'DynamicallyAccessedMemberTypes' on the implicit 'this' parameter of method don't match overridden implicit 'this' parameter of method. All overridden members must have the same 'DynamicallyAccessedMembersAttribute' usage.</summary>
    [DiagnosticRule]
    public static class IL2094
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IL2094);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = TrimCategory.Trimming;
    }

    /// <summary>'DynamicallyAccessedMemberTypes' on the generic parameter of method or type don't match overridden generic parameter method or type. All overridden members must have the same 'DynamicallyAccessedMembersAttribute' usage.</summary>
    [DiagnosticRule]
    public static class IL2095
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IL2095);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = TrimCategory.Trimming;
    }

    /// <summary>Call to 'Type.GetType' method can perform case insensitive lookup of the type, currently trimming can not guarantee presence of all the matching types.</summary>
    [DiagnosticRule]
    public static class IL2096
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IL2096);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = TrimCategory.Trimming;
    }

    /// <summary>Field has 'DynamicallyAccessedMembersAttribute', but that attribute can only be applied to fields of type 'System.Type' or 'System.String'.</summary>
    [DiagnosticRule]
    public static class IL2097
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IL2097);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = TrimCategory.Trimming;
    }

    /// <summary>Parameter of method has 'DynamicallyAccessedMembersAttribute', but that attribute can only be applied to parameters of type 'System.Type' or 'System.String'.</summary>
    [DiagnosticRule]
    public static class IL2098
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IL2098);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = TrimCategory.Trimming;
    }

    /// <summary>Property has 'DynamicallyAccessedMembersAttribute', but that attribute can only be applied to properties of type 'System.Type' or 'System.String'.</summary>
    [DiagnosticRule]
    public static class IL2099
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IL2099);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = TrimCategory.Trimming;
    }

    /// <summary>Value passed to the parameter of method cannot be statically determined as a property accessor.</summary>
    [DiagnosticRule]
    public static class IL2103
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IL2103);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = TrimCategory.Trimming;
    }

    /// <summary>Return type of method has 'DynamicallyAccessedMembersAttribute', but that attribute can only be applied to properties of type 'System.Type' or 'System.String'.</summary>
    [DiagnosticRule]
    public static class IL2106
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IL2106);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = TrimCategory.Trimming;
    }

    /// <summary>Field with 'DynamicallyAccessedMembersAttribute' is accessed via reflection. Trimmer can't guarantee availability of the requirements of the field.</summary>
    [DiagnosticRule]
    public static class IL2110
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IL2110);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = TrimCategory.Trimming;
    }

    /// <summary>Method with parameters or return value with `DynamicallyAccessedMembersAttribute` is accessed via reflection. Trimmer can't guarantee availability of the requirements of the method.</summary>
    [DiagnosticRule]
    public static class IL2111
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IL2111);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = TrimCategory.Trimming;
    }

    /// <summary>'DynamicallyAccessedMembersAttribute' on a type or one of its base types references a member which requires unreferenced code.</summary>
    [DiagnosticRule]
    public static class IL2112
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IL2112);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = TrimCategory.Trimming;
    }

    /// <summary>'DynamicallyAccessedMembersAttribute' on a type or one of its base types references a member which requires unreferenced code.</summary>
    [DiagnosticRule]
    public static class IL2113
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IL2113);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = TrimCategory.Trimming;
    }

    /// <summary>'DynamicallyAccessedMembersAttribute' on a type or one of its base types references a member which has 'DynamicallyAccessedMembersAttribute' requirements.</summary>
    [DiagnosticRule]
    public static class IL2114
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IL2114);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = TrimCategory.Trimming;
    }

    /// <summary>'DynamicallyAccessedMembersAttribute' on a type or one of its base types references a member which has 'DynamicallyAccessedMembersAttribute' requirements.</summary>
    [DiagnosticRule]
    public static class IL2115
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IL2115);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = TrimCategory.Trimming;
    }

    /// <summary>The use of 'RequiresUnreferencedCodeAttribute' on static constructors is disallowed since is a method not callable by the user, is only called by the runtime. Placing the attribute directly on the static constructor will have no effect, instead use 'RequiresUnreferencedCodeAttribute' on the type which will handle warning and silencing from the static constructor.</summary>
    [DiagnosticRule]
    public static class IL2116
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IL2116);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = TrimCategory.Trimming;
    }

    /// <summary>Type name is not assembly qualified.</summary>
    [DiagnosticRule]
    public static class IL2122
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IL2122);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = TrimCategory.Trimming;
    }

    /// <summary>The use of 'RequiresUnreferencedCodeAttribute' on entry points is disallowed since the method will be called from outside the visible app.</summary>
    [DiagnosticRule]
    public static class IL2123
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IL2123);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = TrimCategory.Trimming;
    }

    /// <summary>The provided generic argument cannot be statically determined.</summary>
    [DiagnosticRule]
    public static class IL2124
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IL2124);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = TrimCategory.Trimming;
    }

    /// <summary>Referenced assembly is not marked as trimmable.</summary>
    [DiagnosticRule]
    public static class IL2125
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IL2125);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = TrimCategory.Trimming;
    }

    /// <summary>Trim dataflow analysis took too long to complete. Trim safety cannot be guaranteed.</summary>
    [DiagnosticRule]
    public static class IL2126
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IL2126);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = TrimCategory.Trimming;
    }

    /// <summary>'DynamicallyAccessedMembersAttribute' on extension property is ignored.</summary>
    [DiagnosticRule]
    public static class IL2127
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IL2127);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = TrimCategory.Trimming;
    }

    /// <summary>Avoid accessing Assembly file path when publishing as a single file.</summary>
    [DiagnosticRule]
    public static class IL3000
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IL3000);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = TrimCategory.SingleFile;
    }

    /// <summary>Avoid accessing Assembly file path when publishing as a single file.</summary>
    [DiagnosticRule]
    public static class IL3001
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IL3001);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = TrimCategory.SingleFile;
    }

    /// <summary>Avoid calling members marked with 'RequiresAssemblyFilesAttribute' when publishing as a single-file.</summary>
    [DiagnosticRule]
    public static class IL3002
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IL3002);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = TrimCategory.SingleFile;
    }

    /// <summary>'RequiresAssemblyFilesAttribute' annotations must match across all interface implementations or overrides.</summary>
    [DiagnosticRule]
    public static class IL3003
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IL3003);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = TrimCategory.SingleFile;
    }

    /// <summary>The use of 'RequiresAssemblyFilesAttribute' on static constructors is disallowed since is a method not callable by the user, is only called by the runtime. Placing the attribute directly on the static constructor will have no effect, instead use 'RequiresUnreferencedCodeAttribute' on the type which will handle warning and silencing from the static constructor.</summary>
    [DiagnosticRule]
    public static class IL3004
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IL3004);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = TrimCategory.SingleFile;
    }

    /// <summary>The use of 'RequiresAssemblyFilesAttribute' on entry points is disallowed since the method will be called from outside the visible app.</summary>
    [DiagnosticRule]
    public static class IL3005
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IL3005);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = TrimCategory.SingleFile;
    }

    /// <summary>Calling members annotated with 'RequiresDynamicCodeAttribute' may break functionality when AOT compiling.</summary>
    [DiagnosticRule]
    public static class IL3050
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IL3050);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = TrimCategory.AOT;
    }

    /// <summary>'RequiresDynamicCodeAttribute' annotations must match across all interface implementations or overrides.</summary>
    [DiagnosticRule]
    public static class IL3051
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IL3051);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = TrimCategory.AOT;
    }

    /// <summary>The use of 'RequiresDynamicCodeAttribute' on static constructors is disallowed since is a method not callable by the user, is only called by the runtime. Placing the attribute directly on the static constructor will have no effect, instead use 'RequiresUnreferencedCodeAttribute' on the type which will handle warning and silencing from the static constructor.</summary>
    [DiagnosticRule]
    public static class IL3056
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IL3056);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = TrimCategory.AOT;
    }

    /// <summary>The use of 'RequiresDynamicCodeAttribute' on entry points is disallowed since the method will be called from outside the visible app.</summary>
    [DiagnosticRule]
    public static class IL3057
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IL3057);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = TrimCategory.AOT;
    }

    /// <summary>Referenced assembly is not marked as AOT-compatible.</summary>
    [DiagnosticRule]
    public static class IL3058
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IL3058);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = TrimCategory.AOT;
    }

    /// <summary>Return value does not match FeatureGuard annotations of the property. The check should return false whenever any of the features referenced in the FeatureGuard annotations is disabled.</summary>
    [DiagnosticRule]
    public static class IL4000
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IL4000);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = TrimCategory.AOT;
    }

    /// <summary>Invalid FeatureGuardAttribute.</summary>
    [DiagnosticRule]
    public static class IL4001
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(IL4001);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = TrimCategory.AOT;
    }
}
