using System.Globalization;
using System.Text;

namespace CatalogGen;

// Extracted from Program.cs so it can be exercised by tests: a static local function in a
// top-level-statements program is unreachable from another assembly. Static local functions
// cannot capture, so the move is a relocation and cannot alter behaviour.

internal static class CatalogEmitter
{
    internal static GenerateResult Emit(
        Job job, string packageId, string version,
        SortedDictionary<string, RuleInfo>? upstream, Previous? previous, string? dateOverride)
    {
        SortedDictionary<string, RuleInfo> accepted = new(upstream!, StringComparer.Ordinal);

        // §23.1: a constant is never deleted. Consumers inline const values at their own
        // compile time, so removing one breaks their recompilation. A rule that upstream has
        // retired is carried forward and marked [Obsolete] instead — a warning they can act
        // on, rather than a missing member they cannot.
        List<string> retired = [];
        if (previous is not null)
        {
            foreach ((string id, RuleInfo info) in previous.Rules)
            {
                if (accepted.ContainsKey(id)) continue;
                accepted[id] = info with { Retired = true };
                if (!info.Retired) retired.Add(id);
            }
        }

        List<KeyValuePair<string, RuleInfo>> live = accepted.Where(r => !r.Value.Retired).ToList();
        List<string> categories = accepted.Values.Select(v => v.Category).Distinct()
            .OrderBy(c => c, StringComparer.Ordinal).ToList();
        Console.WriteLine($"distinct categories ({categories.Count}): {string.Join(", ", categories)}");

        // A catalogue repeats very few distinct categories across very many rules — Sonar spends
        // 456 declarations on 13 values. Declare each once and have the rules refer to it: a
        // const initialised from another const is still a compile-time constant, so the rules
        // stay usable as attribute arguments and still fold to the literal in metadata.
        string categoryContainer = job.Container.EndsWith("Rule", StringComparison.Ordinal)
            ? job.Container[..^"Rule".Length] + "Category"
            : job.Container + "Category";

        Dictionary<string, string> categoryNames = new(StringComparer.Ordinal);
        HashSet<string> usedNames = new(StringComparer.Ordinal);
        foreach (string c in categories)
        {
            string baseName = Naming.ToIdentifier(c);
            string name = baseName;
            // Deterministic disambiguation: two categories differing only in punctuation would
            // otherwise silently collapse onto one constant.
            for (int n = 2; !usedNames.Add(name); n++) name = baseName + n.ToString(CultureInfo.InvariantCulture);
            if (name != baseName) Console.WriteLine($"  note: category '{c}' renamed to {name} to avoid a collision");
            categoryNames[c] = name;
        }

        // --- what actually changed -------------------------------------------------
        List<string> added = accepted.Keys.Where(id => previous is null || !previous.Rules.ContainsKey(id)).ToList();
        List<(string Id, string From, string To)> recategorised = previous is null
            ? []
            : accepted.Where(r => previous.Rules.TryGetValue(r.Key, out RuleInfo? old)
                                  && !string.Equals(old.Category, r.Value.Category, StringComparison.Ordinal))
                      .Select(r => (Id: r.Key, From: previous.Rules[r.Key].Category, To: r.Value.Category))
                      .ToList();

        bool versionChanged = previous is null || !string.Equals(previous.SourceVersion, version, StringComparison.Ordinal);
        bool rulesChanged = added.Count > 0 || retired.Count > 0 || recategorised.Count > 0;

        // The date only moves when something else did. Bumping it on every run would make the
        // scheduled job open a pull request every night whose only content was a new date.
        if (previous is not null && !versionChanged && !rulesChanged)
        {
            Console.WriteLine($"unchanged: {packageId} {version}, {live.Count} rules — file left untouched");
            return new GenerateResult(Changed: false, Summary: string.Empty);
        }

        string date = dateOverride ?? DateTime.UtcNow.ToString("yyyy-MM-dd", CultureInfo.InvariantCulture);

        // ---------------------------------------------------------------------------
        // Emit. Output is ordered deterministically so a regeneration produces a diff that
        // shows only genuine upstream change.
        // ---------------------------------------------------------------------------
        StringBuilder sb = new();
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("//     Generated by eng/CatalogGen from the DiagnosticDescriptor instances declared by");
        sb.AppendLine($"//     {packageId} {version} (language: {job.Language}).");
        sb.AppendLine("//     Do not edit by hand: rerun the generator.");
        sb.AppendLine("//");
        sb.AppendLine("//     Only Id, Category and HelpLinkUri are emitted, and only when the descriptor");
        sb.AppendLine("//     actually supplies them. All are facts read from the descriptors. Rule titles");
        sb.AppendLine("//     and descriptions are the upstream vendor's authored content and are");
        sb.AppendLine("//     deliberately not redistributed here.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine();
        // System is needed for one reason only: [Obsolete] on a rule the vendor retired. Emitting it
        // unconditionally leaves an unused directive in every catalogue that has retired nothing,
        // which is all of them today — and it made the generator disagree with its own committed
        // output, so a regeneration would have produced a diff carrying no upstream change at all.
        if (accepted.Values.Any(r => r.Retired)) sb.AppendLine("using System;");
        sb.AppendLine("using DiagnosticCatalog;");
        sb.AppendLine();
        sb.AppendLine("[assembly: CatalogSource(");
        sb.AppendLine($"    source:        \"{packageId}\",");
        sb.AppendLine($"    sourceVersion: \"{version}\",");
        sb.AppendLine($"    generatedOn:   \"{date}\")]");
        sb.AppendLine();
        sb.AppendLine($"namespace {job.Namespace};");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// The diagnostic categories used by {packageId}, declared once each.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("[DiagnosticCategory]");
        sb.AppendLine($"public static class {categoryContainer}");
        sb.AppendLine("{");
        bool firstCategory = true;
        foreach (string c in categories)
        {
            if (!firstCategory) sb.AppendLine();
            firstCategory = false;
            sb.AppendLine($"    /// <summary>The <c>{Naming.Escape(c)}</c> category.</summary>");
            sb.AppendLine($"    public const string {categoryNames[c]} = \"{Naming.Escape(c)}\";");
        }
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// The {packageId} diagnostic rules, as declared by that package's analyzers.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"public static class {job.Container}");
        sb.AppendLine("{");

        bool first = true;
        foreach ((string id, RuleInfo info) in accepted)
        {
            if (!first) sb.AppendLine();
            first = false;
            bool hasHelp = !string.IsNullOrWhiteSpace(info.HelpLinkUri);
            sb.AppendLine("    /// <summary>");
            sb.AppendLine($"    /// Rule <c>{id}</c>, category <c>{Naming.Escape(info.Category)}</c>.");
            if (info.Retired)
                sb.AppendLine($"    /// No longer declared by {packageId} as of {version}.");
            if (hasHelp) sb.AppendLine($"    /// See <see href=\"{Naming.Escape(info.HelpLinkUri)}\"/>.");
            sb.AppendLine("    /// </summary>");
            if (info.Retired)
                sb.AppendLine($"    [Obsolete(\"{Naming.Escape(id)} is no longer declared by {packageId} as of {version}. " +
                              "Kept so that removing it does not break recompilation; remove your suppression.\")]");
            sb.AppendLine("    [DiagnosticRule]");
            sb.AppendLine($"    public static class {id}");
            sb.AppendLine("    {");
            sb.AppendLine("        /// <summary>The canonical identifier of this diagnostic.</summary>");
            sb.AppendLine($"        public const string Id = nameof({id});");
            sb.AppendLine();
            sb.AppendLine("        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>");
            sb.AppendLine($"        public const string Category = {categoryContainer}.{categoryNames[info.Category]};");
            if (hasHelp)
            {
                sb.AppendLine();
                sb.AppendLine("        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>");
                sb.AppendLine($"        public const string HelpLinkUri = \"{Naming.Escape(info.HelpLinkUri)}\";");
            }
            sb.AppendLine("    }");
        }

        sb.AppendLine("}");

        Directory.CreateDirectory(Path.GetDirectoryName(job.Output)!);
        File.WriteAllText(job.Output, sb.ToString().ReplaceLineEndings("\n"), new UTF8Encoding(false));
        Console.WriteLine($"wrote {live.Count} live rules " +
                          $"({accepted.Count - live.Count} retired) to {job.Output}");

        // --- human-readable summary for the pull request ---------------------------
        StringBuilder md = new();
        string fromTo = previous is null
            ? version
            : versionChanged ? $"{previous.SourceVersion} → {version}" : version;
        md.AppendLine($"#### {job.Namespace} — {packageId} {fromTo}");
        md.AppendLine();
        if (!rulesChanged)
        {
            md.AppendLine("No rule changes. Only the mirrored upstream version moved.");
        }
        else
        {
            if (added.Count > 0)
            {
                md.AppendLine($"**Added ({added.Count}):**");
                foreach (string id in added.Take(50))
                    md.AppendLine($"- `{id}` — {accepted[id].Category}");
                if (added.Count > 50) md.AppendLine($"- …and {added.Count - 50} more");
                md.AppendLine();
            }
            if (recategorised.Count > 0)
            {
                md.AppendLine($"**Recategorised ({recategorised.Count}):**");
                foreach ((string Id, string From, string To) r in recategorised)
                    md.AppendLine($"- `{r.Id}` — {r.From} → {r.To}");
                md.AppendLine();
            }
            if (retired.Count > 0)
            {
                md.AppendLine($"**Retired upstream ({retired.Count}) — kept and marked `[Obsolete]`:**");
                foreach (string id in retired)
                    md.AppendLine($"- `{id}`");
                md.AppendLine();
                md.AppendLine("> Constants are never deleted: consumers inline them, so removing one breaks " +
                              "their recompilation. Deleting these is a major version (§23.1).");
                md.AppendLine();
            }
        }
        md.AppendLine($"{live.Count} live rules, {categories.Count} categories.");

        return new GenerateResult(Changed: true, Summary: md.ToString().TrimEnd() + "\n");
    }
}
