// <auto-generated>
//     Generated by eng/CatalogGen from the DiagnosticDescriptor instances declared by
//     DiagnosticCatalog.Analyzers 1.0.0.0 (language: cs).
//     Do not edit by hand: rerun the generator.
//
//     Only Id, Category, Title and HelpLinkUri are emitted, and only when the
//     descriptor actually supplies them. A rule's title is reproduced verbatim as its
//     documentation comment: it is the one sentence that says what the rule is about,
//     and it is DiagnosticCatalog.Analyzers's own wording. Rule descriptions and message
//     formats are the vendor's documentation and are not redistributed here.
// </auto-generated>

using DiagnosticCatalog;

[assembly: CatalogSource(
    source:        "DiagnosticCatalog.Analyzers",
    sourceVersion: "1.0.0.0",
    generatedOn:   "2026-07-31")]

namespace DiagnosticCatalog.Self;

/// <summary>
/// The diagnostic categories used by DiagnosticCatalog.Analyzers, declared once each.
/// </summary>
[DiagnosticCategory]
public static class DcatCategory
{
    /// <summary>The <c>DiagnosticCatalog</c> category.</summary>
    public const string DiagnosticCatalog = "DiagnosticCatalog";
}

/// <summary>
/// The DiagnosticCatalog.Analyzers diagnostic rules, as declared by that package's analyzers.
/// </summary>
public static class DcatRule
{
    /// <summary>Category and Id must reference the same diagnostic rule.</summary>
    [DiagnosticRule]
    public static class DCAT0001
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(DCAT0001);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = DcatCategory.DiagnosticCatalog;
    }

    /// <summary>A diagnostic rule must be declared as a static non-generic class.</summary>
    [DiagnosticRule]
    public static class DCAT0002
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(DCAT0002);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = DcatCategory.DiagnosticCatalog;
    }

    /// <summary>A diagnostic rule must expose a public constant string named Id.</summary>
    [DiagnosticRule]
    public static class DCAT0003
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(DCAT0003);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = DcatCategory.DiagnosticCatalog;
    }

    /// <summary>A diagnostic rule must expose a public constant string named Category.</summary>
    [DiagnosticRule]
    public static class DCAT0004
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(DCAT0004);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = DcatCategory.DiagnosticCatalog;
    }

    /// <summary>Use a diagnostic catalog reference instead of string literals.</summary>
    [DiagnosticRule]
    public static class DCAT0006
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(DCAT0006);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = DcatCategory.DiagnosticCatalog;
    }

    /// <summary>Suppression mixes a catalog reference with a string literal.</summary>
    [DiagnosticRule]
    public static class DCAT0007
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(DCAT0007);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = DcatCategory.DiagnosticCatalog;
    }

    /// <summary>UnconditionalSuppressMessage only accepts IL#### identifiers.</summary>
    [DiagnosticRule]
    public static class DCAT0009
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(DCAT0009);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = DcatCategory.DiagnosticCatalog;
    }
}
