// <auto-generated>
//     Generated by eng/CatalogGen from the DiagnosticDescriptor instances declared by
//     MSTest.Analyzers 4.3.3 (language: cs).
//     Do not edit by hand: rerun the generator.
//
//     Only Id, Category, Title and HelpLinkUri are emitted, and only when the
//     descriptor actually supplies them. A rule's title is reproduced verbatim as its
//     documentation comment: it is the one sentence that says what the rule is about,
//     and it is MSTest.Analyzers's own wording. Rule descriptions and message
//     formats are the vendor's documentation and are not redistributed here.
// </auto-generated>

using DiagnosticCatalog;

[assembly: CatalogSource(
    source:        "MSTest.Analyzers",
    sourceVersion: "4.3.3",
    generatedOn:   "2026-08-05")]

namespace DiagnosticCatalog.MSTest;

/// <summary>
/// The diagnostic categories used by MSTest.Analyzers, declared once each.
/// </summary>
/// <remarks>
/// INTERNAL by design. A category is reachable only through the rule that carries it:
/// write <c>SomeRule.Sxxxx.Category</c>, never the category constant directly. The two
/// spellings fold to the same string today and stop agreeing the day the vendor moves the
/// rule to another category -- the rule member follows, a category named on its own does
/// not, and the suppression silently stops matching. Keeping this class out of the public
/// surface makes that decoupling unwritable rather than merely discouraged.
/// The public <c>Category</c> constant on each rule is initialised from here and folds to
/// the literal at compile time, so a consumer loses nothing.
/// </remarks>
[DiagnosticCategory]
internal static class MSTestCategory
{
    /// <summary>The <c>Design</c> category.</summary>
    public const string Design = "Design";

    /// <summary>The <c>Performance</c> category.</summary>
    public const string Performance = "Performance";

    /// <summary>The <c>Usage</c> category.</summary>
    public const string Usage = "Usage";
}

/// <summary>
/// The MSTest.Analyzers diagnostic rules, as declared by that package's analyzers.
/// </summary>
public static class MSTestRule
{
    /// <summary>Explicitly enable or disable tests parallelization.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0001"/>.</remarks>
    [DiagnosticRule]
    public static class MSTEST0001
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(MSTEST0001);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = MSTestCategory.Performance;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0001";
    }

    /// <summary>Test classes should have valid layout.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0002"/>.</remarks>
    [DiagnosticRule]
    public static class MSTEST0002
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(MSTEST0002);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = MSTestCategory.Usage;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0002";
    }

    /// <summary>Test methods should have valid layout.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0003"/>.</remarks>
    [DiagnosticRule]
    public static class MSTEST0003
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(MSTEST0003);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = MSTestCategory.Usage;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0003";
    }

    /// <summary>Public types should be test classes.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0004"/>.</remarks>
    [DiagnosticRule]
    public static class MSTEST0004
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(MSTEST0004);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = MSTestCategory.Design;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0004";
    }

    /// <summary>Test context property should have valid layout.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0005"/>.</remarks>
    [DiagnosticRule]
    public static class MSTEST0005
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(MSTEST0005);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = MSTestCategory.Usage;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0005";
    }

    /// <summary>[WorkItem] can only be set on methods marked with [TestMethod].</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0007"/>.</remarks>
    [DiagnosticRule]
    public static class MSTEST0007
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(MSTEST0007);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = MSTestCategory.Usage;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0007";
    }

    /// <summary>TestInitialize method should have valid layout.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0008"/>.</remarks>
    [DiagnosticRule]
    public static class MSTEST0008
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(MSTEST0008);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = MSTestCategory.Usage;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0008";
    }

    /// <summary>TestCleanup method should have valid layout.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0009"/>.</remarks>
    [DiagnosticRule]
    public static class MSTEST0009
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(MSTEST0009);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = MSTestCategory.Usage;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0009";
    }

    /// <summary>ClassInitialize methods should have valid layout.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0010"/>.</remarks>
    [DiagnosticRule]
    public static class MSTEST0010
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(MSTEST0010);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = MSTestCategory.Usage;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0010";
    }

    /// <summary>ClassCleanup methods should have valid layout.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0011"/>.</remarks>
    [DiagnosticRule]
    public static class MSTEST0011
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(MSTEST0011);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = MSTestCategory.Usage;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0011";
    }

    /// <summary>AssemblyInitialize methods should have valid layout.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0012"/>.</remarks>
    [DiagnosticRule]
    public static class MSTEST0012
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(MSTEST0012);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = MSTestCategory.Usage;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0012";
    }

    /// <summary>AssemblyCleanup methods should have valid layout.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0013"/>.</remarks>
    [DiagnosticRule]
    public static class MSTEST0013
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(MSTEST0013);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = MSTestCategory.Usage;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0013";
    }

    /// <summary>DataRow should be valid.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0014"/>.</remarks>
    [DiagnosticRule]
    public static class MSTEST0014
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(MSTEST0014);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = MSTestCategory.Usage;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0014";
    }

    /// <summary>Test method should not be ignored.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0015"/>.</remarks>
    [DiagnosticRule]
    public static class MSTEST0015
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(MSTEST0015);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = MSTestCategory.Design;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0015";
    }

    /// <summary>Test class should have test method.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0016"/>.</remarks>
    [DiagnosticRule]
    public static class MSTEST0016
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(MSTEST0016);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = MSTestCategory.Design;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0016";
    }

    /// <summary>Assertion arguments should be passed in the correct order.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0017"/>.</remarks>
    [DiagnosticRule]
    public static class MSTEST0017
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(MSTEST0017);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = MSTestCategory.Usage;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0017";
    }

    /// <summary>DynamicData should be valid.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0018"/>.</remarks>
    [DiagnosticRule]
    public static class MSTEST0018
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(MSTEST0018);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = MSTestCategory.Usage;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0018";
    }

    /// <summary>Prefer TestInitialize methods over constructors.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0019"/>.</remarks>
    [DiagnosticRule]
    public static class MSTEST0019
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(MSTEST0019);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = MSTestCategory.Design;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0019";
    }

    /// <summary>Prefer constructors over TestInitialize methods.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0020"/>.</remarks>
    [DiagnosticRule]
    public static class MSTEST0020
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(MSTEST0020);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = MSTestCategory.Design;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0020";
    }

    /// <summary>Prefer 'Dispose' over TestCleanup methods.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0021"/>.</remarks>
    [DiagnosticRule]
    public static class MSTEST0021
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(MSTEST0021);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = MSTestCategory.Design;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0021";
    }

    /// <summary>Prefer TestCleanup over 'Dispose' methods.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0022"/>.</remarks>
    [DiagnosticRule]
    public static class MSTEST0022
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(MSTEST0022);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = MSTestCategory.Design;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0022";
    }

    /// <summary>Do not negate boolean assertions.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0023"/>.</remarks>
    [DiagnosticRule]
    public static class MSTEST0023
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(MSTEST0023);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = MSTestCategory.Usage;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0023";
    }

    /// <summary>Do not store TestContext in a static member.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0024"/>.</remarks>
    [DiagnosticRule]
    public static class MSTEST0024
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(MSTEST0024);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = MSTestCategory.Usage;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0024";
    }

    /// <summary>Use 'Assert.Fail' instead of an always-failing assert.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0025"/>.</remarks>
    [DiagnosticRule]
    public static class MSTEST0025
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(MSTEST0025);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = MSTestCategory.Design;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0025";
    }

    /// <summary>Avoid conditional access in assertions.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0026"/>.</remarks>
    [DiagnosticRule]
    public static class MSTEST0026
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(MSTEST0026);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = MSTestCategory.Usage;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0026";
    }

    /// <summary>Public methods should be test methods.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0029"/>.</remarks>
    [DiagnosticRule]
    public static class MSTEST0029
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(MSTEST0029);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = MSTestCategory.Design;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0029";
    }

    /// <summary>Type containing '[TestMethod]' should be marked with '[TestClass]'.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0030"/>.</remarks>
    [DiagnosticRule]
    public static class MSTEST0030
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(MSTEST0030);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = MSTestCategory.Usage;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0030";
    }

    /// <summary>'System.ComponentModel.DescriptionAttribute' has no effect on test methods.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0031"/>.</remarks>
    [DiagnosticRule]
    public static class MSTEST0031
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(MSTEST0031);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = MSTestCategory.Usage;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0031";
    }

    /// <summary>Assertion condition is always true.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0032"/>.</remarks>
    [DiagnosticRule]
    public static class MSTEST0032
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(MSTEST0032);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = MSTestCategory.Design;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0032";
    }

    /// <summary>'[DeploymentItem]' can be specified only on test class or test method.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0035"/>.</remarks>
    [DiagnosticRule]
    public static class MSTEST0035
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(MSTEST0035);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = MSTestCategory.Usage;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0035";
    }

    /// <summary>Do not use shadowing.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0036"/>.</remarks>
    [DiagnosticRule]
    public static class MSTEST0036
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(MSTEST0036);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = MSTestCategory.Design;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0036";
    }

    /// <summary>Use proper 'Assert' methods.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0037"/>.</remarks>
    [DiagnosticRule]
    public static class MSTEST0037
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(MSTEST0037);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = MSTestCategory.Usage;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0037";
    }

    /// <summary>Don't use 'Assert.AreSame' or 'Assert.AreNotSame' with value types.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0038"/>.</remarks>
    [DiagnosticRule]
    public static class MSTEST0038
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(MSTEST0038);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = MSTestCategory.Usage;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0038";
    }

    /// <summary>Do not assert inside 'async void' contexts.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0040"/>.</remarks>
    [DiagnosticRule]
    public static class MSTEST0040
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(MSTEST0040);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = MSTestCategory.Usage;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0040";
    }

    /// <summary>Use 'ConditionBaseAttribute' on test classes.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0041"/>.</remarks>
    [DiagnosticRule]
    public static class MSTEST0041
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(MSTEST0041);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = MSTestCategory.Usage;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0041";
    }

    /// <summary>Avoid duplicated 'DataRow' entries.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0042"/>.</remarks>
    [DiagnosticRule]
    public static class MSTEST0042
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(MSTEST0042);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = MSTestCategory.Usage;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0042";
    }

    /// <summary>Use retry attribute on test method or test class.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0043"/>.</remarks>
    [DiagnosticRule]
    public static class MSTEST0043
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(MSTEST0043);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = MSTestCategory.Usage;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0043";
    }

    /// <summary>Prefer 'TestMethod' over 'DataTestMethod'.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0044"/>.</remarks>
    [DiagnosticRule]
    public static class MSTEST0044
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(MSTEST0044);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = MSTestCategory.Design;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0044";
    }

    /// <summary>Use 'CooperativeCancellation = true' with '[Timeout]'.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0045"/>.</remarks>
    [DiagnosticRule]
    public static class MSTEST0045
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(MSTEST0045);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = MSTestCategory.Design;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0045";
    }

    /// <summary>Use 'Assert' instead of 'StringAssert'.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0046"/>.</remarks>
    [DiagnosticRule]
    public static class MSTEST0046
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(MSTEST0046);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = MSTestCategory.Usage;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0046";
    }

    /// <summary>TestContext property cannot be accessed in this context.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0048"/>.</remarks>
    [DiagnosticRule]
    public static class MSTEST0048
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(MSTEST0048);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = MSTestCategory.Usage;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0048";
    }

    /// <summary>Flow TestContext.CancellationToken to async operations.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0049"/>.</remarks>
    [DiagnosticRule]
    public static class MSTEST0049
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(MSTEST0049);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = MSTestCategory.Usage;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0049";
    }

    /// <summary>GlobalTestInitialize and GlobalTestCleanup methods should have valid layout.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0050"/>.</remarks>
    [DiagnosticRule]
    public static class MSTEST0050
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(MSTEST0050);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = MSTestCategory.Usage;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0050";
    }

    /// <summary>Assert.Throws should contain only a single statement/expression.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0051"/>.</remarks>
    [DiagnosticRule]
    public static class MSTEST0051
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(MSTEST0051);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = MSTestCategory.Usage;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0051";
    }

    /// <summary>Avoid passing an explicit 'DynamicDataSourceType' and use the default auto detect behavior.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0052"/>.</remarks>
    [DiagnosticRule]
    public static class MSTEST0052
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(MSTEST0052);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = MSTestCategory.Usage;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0052";
    }

    /// <summary>Use TestContext.CancellationToken instead of TestContext.CancellationTokenSource.Token.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0054"/>.</remarks>
    [DiagnosticRule]
    public static class MSTEST0054
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(MSTEST0054);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = MSTestCategory.Usage;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0054";
    }

    /// <summary>Do not ignore the return value of string methods.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0055"/>.</remarks>
    [DiagnosticRule]
    public static class MSTEST0055
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(MSTEST0055);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = MSTestCategory.Usage;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0055";
    }

    /// <summary>TestMethodAttribute should set DisplayName correctly.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0056"/>.</remarks>
    [DiagnosticRule]
    public static class MSTEST0056
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(MSTEST0056);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = MSTestCategory.Usage;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0056";
    }

    /// <summary>TestMethodAttribute derived class should propagate source information.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0057"/>.</remarks>
    [DiagnosticRule]
    public static class MSTEST0057
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(MSTEST0057);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = MSTestCategory.Usage;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0057";
    }

    /// <summary>Do not use asserts in catch blocks.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0058"/>.</remarks>
    [DiagnosticRule]
    public static class MSTEST0058
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(MSTEST0058);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = MSTestCategory.Usage;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0058";
    }

    /// <summary>Do not use both '[Parallelize]' and '[DoNotParallelize]' attributes.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0059"/>.</remarks>
    [DiagnosticRule]
    public static class MSTEST0059
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(MSTEST0059);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = MSTestCategory.Usage;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0059";
    }

    /// <summary>Avoid duplicate test method attributes.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0060"/>.</remarks>
    [DiagnosticRule]
    public static class MSTEST0060
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(MSTEST0060);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = MSTestCategory.Usage;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0060";
    }

    /// <summary>Use '[OSCondition]' attribute instead of 'RuntimeInformation.IsOSPlatform' calls with early return or 'Assert.Inconclusive'.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0061"/>.</remarks>
    [DiagnosticRule]
    public static class MSTEST0061
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(MSTEST0061);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = MSTestCategory.Usage;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0061";
    }

    /// <summary>Avoid using 'out' or 'ref' parameters in test methods.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0062"/>.</remarks>
    [DiagnosticRule]
    public static class MSTEST0062
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(MSTEST0062);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = MSTestCategory.Usage;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0062";
    }

    /// <summary>Test classes should have valid constructors.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0063"/>.</remarks>
    [DiagnosticRule]
    public static class MSTEST0063
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(MSTEST0063);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = MSTestCategory.Usage;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0063";
    }

    /// <summary>Prefer async assertion methods.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0064"/>.</remarks>
    [DiagnosticRule]
    public static class MSTEST0064
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(MSTEST0064);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = MSTestCategory.Usage;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0064";
    }

    /// <summary>Avoid Assert.AreEqual on collection types.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0065"/>.</remarks>
    [DiagnosticRule]
    public static class MSTEST0065
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(MSTEST0065);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = MSTestCategory.Usage;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0065";
    }

    /// <summary>'[Ignore]' should specify a justification.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0066"/>.</remarks>
    [DiagnosticRule]
    public static class MSTEST0066
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(MSTEST0066);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = MSTestCategory.Design;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0066";
    }

    /// <summary>Avoid synchronously blocking calls such as 'Thread.Sleep', 'Task.Wait', 'Task.WaitAll', 'Task.WaitAny' or 'Task&lt;TResult&gt;.Result' in test code.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0067"/>.</remarks>
    [DiagnosticRule]
    public static class MSTEST0067
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(MSTEST0067);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = MSTestCategory.Performance;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0067";
    }

    /// <summary>Use 'Assert' instead of 'CollectionAssert'.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0068"/>.</remarks>
    [DiagnosticRule]
    public static class MSTEST0068
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(MSTEST0068);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = MSTestCategory.Usage;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0068";
    }

    /// <summary>'[MemberCondition]' arguments should be valid.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0070"/>.</remarks>
    [DiagnosticRule]
    public static class MSTEST0070
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(MSTEST0070);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = MSTestCategory.Usage;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0070";
    }

    /// <summary>Test method should not specify a display name equal to its name.</summary>
    /// <remarks>See <see href="https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0071"/>.</remarks>
    [DiagnosticRule]
    public static class MSTEST0071
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(MSTEST0071);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = MSTestCategory.Usage;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://learn.microsoft.com/dotnet/core/testing/mstest-analyzers/mstest0071";
    }
}
