// <auto-generated>
//     Generated by eng/CatalogGen from the DiagnosticDescriptor instances declared by
//     NUnit.Analyzers 4.14.0 (language: cs).
//     Do not edit by hand: rerun the generator.
//
//     Only Id, Category, Title and HelpLinkUri are emitted, and only when the
//     descriptor actually supplies them. A rule's title is reproduced verbatim as its
//     documentation comment: it is the one sentence that says what the rule is about,
//     and it is NUnit.Analyzers's own wording. Rule descriptions and message
//     formats are the vendor's documentation and are not redistributed here.
// </auto-generated>

using DiagnosticCatalog;

[assembly: CatalogSource(
    source:        "NUnit.Analyzers",
    sourceVersion: "4.14.0",
    generatedOn:   "2026-08-05")]

namespace DiagnosticCatalog.NUnit;

/// <summary>
/// The diagnostic categories used by NUnit.Analyzers, declared once each.
/// </summary>
/// <remarks>
/// INTERNAL by design. A category is reachable only through the rule that carries it:
/// write <c>SomeRule.Sxxxx.Category</c>, never the category constant directly. The two
/// spellings fold to the same string today and stop agreeing the day the vendor moves the
/// rule to another category -- the rule member follows, a category named on its own does
/// not, and the suppression silently stops matching. Keeping this class out of the public
/// surface makes that decoupling unwritable rather than merely discouraged.
/// The public <c>Category</c> constant on each rule is initialised from here and folds to
/// the literal at compile time, so a consumer loses nothing.
/// </remarks>
[DiagnosticCategory]
internal static class NUnitCategory
{
    /// <summary>The <c>Assertion</c> category.</summary>
    public const string Assertion = "Assertion";

    /// <summary>The <c>Structure</c> category.</summary>
    public const string Structure = "Structure";

    /// <summary>The <c>Style</c> category.</summary>
    public const string Style = "Style";
}

/// <summary>
/// The NUnit.Analyzers diagnostic rules, as declared by that package's analyzers.
/// </summary>
public static class NUnitRule
{
    /// <summary>The individual arguments provided by a TestCaseAttribute must match the type of the corresponding parameter of the method.</summary>
    /// <remarks>See <see href="https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit1001.md"/>.</remarks>
    [DiagnosticRule]
    public static class NUnit1001
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(NUnit1001);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = NUnitCategory.Structure;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit1001.md";
    }

    /// <summary>The TestCaseSource should use nameof operator to specify target.</summary>
    /// <remarks>See <see href="https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit1002.md"/>.</remarks>
    [DiagnosticRule]
    public static class NUnit1002
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(NUnit1002);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = NUnitCategory.Structure;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit1002.md";
    }

    /// <summary>The TestCaseAttribute provided too few arguments.</summary>
    /// <remarks>See <see href="https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit1003.md"/>.</remarks>
    [DiagnosticRule]
    public static class NUnit1003
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(NUnit1003);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = NUnitCategory.Structure;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit1003.md";
    }

    /// <summary>The TestCaseAttribute provided too many arguments.</summary>
    /// <remarks>See <see href="https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit1004.md"/>.</remarks>
    [DiagnosticRule]
    public static class NUnit1004
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(NUnit1004);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = NUnitCategory.Structure;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit1004.md";
    }

    /// <summary>The type of the value specified via ExpectedResult must match the return type of the method.</summary>
    /// <remarks>See <see href="https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit1005.md"/>.</remarks>
    [DiagnosticRule]
    public static class NUnit1005
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(NUnit1005);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = NUnitCategory.Structure;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit1005.md";
    }

    /// <summary>ExpectedResult must not be specified when the method returns void.</summary>
    /// <remarks>See <see href="https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit1006.md"/>.</remarks>
    [DiagnosticRule]
    public static class NUnit1006
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(NUnit1006);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = NUnitCategory.Structure;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit1006.md";
    }

    /// <summary>The method has non-void return type, but no result is expected in ExpectedResult.</summary>
    /// <remarks>See <see href="https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit1007.md"/>.</remarks>
    [DiagnosticRule]
    public static class NUnit1007
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(NUnit1007);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = NUnitCategory.Structure;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit1007.md";
    }

    /// <summary>Specifying ParallelScope.Self on assembly level has no effect.</summary>
    /// <remarks>See <see href="https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit1008.md"/>.</remarks>
    [DiagnosticRule]
    public static class NUnit1008
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(NUnit1008);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = NUnitCategory.Structure;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit1008.md";
    }

    /// <summary>One may not specify ParallelScope.Children on a non-parameterized test method.</summary>
    /// <remarks>See <see href="https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit1009.md"/>.</remarks>
    [DiagnosticRule]
    public static class NUnit1009
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(NUnit1009);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = NUnitCategory.Structure;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit1009.md";
    }

    /// <summary>One may not specify ParallelScope.Fixtures on a test method.</summary>
    /// <remarks>See <see href="https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit1010.md"/>.</remarks>
    [DiagnosticRule]
    public static class NUnit1010
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(NUnit1010);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = NUnitCategory.Structure;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit1010.md";
    }

    /// <summary>The TestCaseSource argument does not specify an existing member.</summary>
    /// <remarks>See <see href="https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit1011.md"/>.</remarks>
    [DiagnosticRule]
    public static class NUnit1011
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(NUnit1011);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = NUnitCategory.Structure;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit1011.md";
    }

    /// <summary>The async test method must have a non-void return type.</summary>
    /// <remarks>See <see href="https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit1012.md"/>.</remarks>
    [DiagnosticRule]
    public static class NUnit1012
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(NUnit1012);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = NUnitCategory.Structure;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit1012.md";
    }

    /// <summary>The async test method must have a non-generic Task return type when no result is expected.</summary>
    /// <remarks>See <see href="https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit1013.md"/>.</remarks>
    [DiagnosticRule]
    public static class NUnit1013
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(NUnit1013);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = NUnitCategory.Structure;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit1013.md";
    }

    /// <summary>The async test method must have a Task&lt;T&gt; return type when a result is expected.</summary>
    /// <remarks>See <see href="https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit1014.md"/>.</remarks>
    [DiagnosticRule]
    public static class NUnit1014
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(NUnit1014);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = NUnitCategory.Structure;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit1014.md";
    }

    /// <summary>The source type does not implement I(Async)Enumerable.</summary>
    /// <remarks>See <see href="https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit1015.md"/>.</remarks>
    [DiagnosticRule]
    public static class NUnit1015
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(NUnit1015);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = NUnitCategory.Structure;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit1015.md";
    }

    /// <summary>The source type does not have a default constructor.</summary>
    /// <remarks>See <see href="https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit1016.md"/>.</remarks>
    [DiagnosticRule]
    public static class NUnit1016
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(NUnit1016);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = NUnitCategory.Structure;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit1016.md";
    }

    /// <summary>The specified source is not static.</summary>
    /// <remarks>See <see href="https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit1017.md"/>.</remarks>
    [DiagnosticRule]
    public static class NUnit1017
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(NUnit1017);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = NUnitCategory.Structure;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit1017.md";
    }

    /// <summary>The number of parameters provided by the TestCaseSource does not match the number of parameters in the target method.</summary>
    /// <remarks>See <see href="https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit1018.md"/>.</remarks>
    [DiagnosticRule]
    public static class NUnit1018
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(NUnit1018);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = NUnitCategory.Structure;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit1018.md";
    }

    /// <summary>The source specified by the TestCaseSource does not return an I(Async)Enumerable or a type that implements I(Async)Enumerable.</summary>
    /// <remarks>See <see href="https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit1019.md"/>.</remarks>
    [DiagnosticRule]
    public static class NUnit1019
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(NUnit1019);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = NUnitCategory.Structure;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit1019.md";
    }

    /// <summary>The TestCaseSource provides parameters to a source - field or property - that expects no parameters.</summary>
    /// <remarks>See <see href="https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit1020.md"/>.</remarks>
    [DiagnosticRule]
    public static class NUnit1020
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(NUnit1020);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = NUnitCategory.Structure;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit1020.md";
    }

    /// <summary>The ValueSource should use nameof operator to specify target.</summary>
    /// <remarks>See <see href="https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit1021.md"/>.</remarks>
    [DiagnosticRule]
    public static class NUnit1021
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(NUnit1021);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = NUnitCategory.Structure;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit1021.md";
    }

    /// <summary>The specified source is not static.</summary>
    /// <remarks>See <see href="https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit1022.md"/>.</remarks>
    [DiagnosticRule]
    public static class NUnit1022
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(NUnit1022);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = NUnitCategory.Structure;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit1022.md";
    }

    /// <summary>The target method expects parameters which cannot be supplied by the ValueSource.</summary>
    /// <remarks>See <see href="https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit1023.md"/>.</remarks>
    [DiagnosticRule]
    public static class NUnit1023
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(NUnit1023);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = NUnitCategory.Structure;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit1023.md";
    }

    /// <summary>The source specified by the ValueSource does not return an I(Async)Enumerable or a type that implements I(Async)Enumerable.</summary>
    /// <remarks>See <see href="https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit1024.md"/>.</remarks>
    [DiagnosticRule]
    public static class NUnit1024
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(NUnit1024);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = NUnitCategory.Structure;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit1024.md";
    }

    /// <summary>The ValueSource argument does not specify an existing member.</summary>
    /// <remarks>See <see href="https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit1025.md"/>.</remarks>
    [DiagnosticRule]
    public static class NUnit1025
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(NUnit1025);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = NUnitCategory.Structure;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit1025.md";
    }

    /// <summary>The test or setup/teardown method is not public.</summary>
    /// <remarks>See <see href="https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit1026.md"/>.</remarks>
    [DiagnosticRule]
    public static class NUnit1026
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(NUnit1026);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = NUnitCategory.Structure;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit1026.md";
    }

    /// <summary>The test method has parameters, but no arguments are supplied by attributes.</summary>
    /// <remarks>See <see href="https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit1027.md"/>.</remarks>
    [DiagnosticRule]
    public static class NUnit1027
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(NUnit1027);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = NUnitCategory.Structure;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit1027.md";
    }

    /// <summary>The non-test method is public.</summary>
    /// <remarks>See <see href="https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit1028.md"/>.</remarks>
    [DiagnosticRule]
    public static class NUnit1028
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(NUnit1028);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = NUnitCategory.Structure;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit1028.md";
    }

    /// <summary>The number of parameters provided by the TestCaseSource does not match the number of parameters in the Test method.</summary>
    /// <remarks>See <see href="https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit1029.md"/>.</remarks>
    [DiagnosticRule]
    public static class NUnit1029
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(NUnit1029);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = NUnitCategory.Structure;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit1029.md";
    }

    /// <summary>The type of parameter provided by the TestCaseSource does not match the type of the parameter in the Test method.</summary>
    /// <remarks>See <see href="https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit1030.md"/>.</remarks>
    [DiagnosticRule]
    public static class NUnit1030
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(NUnit1030);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = NUnitCategory.Structure;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit1030.md";
    }

    /// <summary>The individual arguments provided by a ValuesAttribute must match the type of the corresponding parameter of the method.</summary>
    /// <remarks>See <see href="https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit1031.md"/>.</remarks>
    [DiagnosticRule]
    public static class NUnit1031
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(NUnit1031);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = NUnitCategory.Structure;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit1031.md";
    }

    /// <summary>An IDisposable field/property should be Disposed in a TearDown method.</summary>
    /// <remarks>See <see href="https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit1032.md"/>.</remarks>
    [DiagnosticRule]
    public static class NUnit1032
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(NUnit1032);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = NUnitCategory.Structure;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit1032.md";
    }

    /// <summary>The Write methods on TestContext will be marked as Obsolete and eventually removed.</summary>
    /// <remarks>See <see href="https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit1033.md"/>.</remarks>
    [DiagnosticRule]
    public static class NUnit1033
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(NUnit1033);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = NUnitCategory.Structure;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit1033.md";
    }

    /// <summary>Base TestFixtures should be abstract.</summary>
    /// <remarks>See <see href="https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit1034.md"/>.</remarks>
    [DiagnosticRule]
    public static class NUnit1034
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(NUnit1034);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = NUnitCategory.Structure;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit1034.md";
    }

    /// <summary>The 'step' parameter to Range cannot be zero.</summary>
    /// <remarks>See <see href="https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit1035.md"/>.</remarks>
    [DiagnosticRule]
    public static class NUnit1035
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(NUnit1035);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = NUnitCategory.Structure;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit1035.md";
    }

    /// <summary>The value for 'from' must be less than 'to' when 'step' is positive.</summary>
    /// <remarks>See <see href="https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit1036.md"/>.</remarks>
    [DiagnosticRule]
    public static class NUnit1036
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(NUnit1036);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = NUnitCategory.Structure;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit1036.md";
    }

    /// <summary>The value for 'from' must be greater than 'to' when 'step' is negative.</summary>
    /// <remarks>See <see href="https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit1037.md"/>.</remarks>
    [DiagnosticRule]
    public static class NUnit1037
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(NUnit1037);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = NUnitCategory.Structure;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit1037.md";
    }

    /// <summary>The type of the attribute values doesn't match the parameter type.</summary>
    /// <remarks>See <see href="https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit1038.md"/>.</remarks>
    [DiagnosticRule]
    public static class NUnit1038
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(NUnit1038);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = NUnitCategory.Structure;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit1038.md";
    }

    /// <summary>Consider using Assert.That(expr, Is.False) instead of ClassicAssert.False(expr).</summary>
    /// <remarks>See <see href="https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit2001.md"/>.</remarks>
    [DiagnosticRule]
    public static class NUnit2001
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(NUnit2001);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = NUnitCategory.Assertion;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit2001.md";
    }

    /// <summary>Consider using Assert.That(expr, Is.False) instead of ClassicAssert.IsFalse(expr).</summary>
    /// <remarks>See <see href="https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit2002.md"/>.</remarks>
    [DiagnosticRule]
    public static class NUnit2002
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(NUnit2002);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = NUnitCategory.Assertion;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit2002.md";
    }

    /// <summary>Consider using Assert.That(expr, Is.True) instead of ClassicAssert.IsTrue(expr).</summary>
    /// <remarks>See <see href="https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit2003.md"/>.</remarks>
    [DiagnosticRule]
    public static class NUnit2003
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(NUnit2003);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = NUnitCategory.Assertion;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit2003.md";
    }

    /// <summary>Consider using Assert.That(expr, Is.True) instead of ClassicAssert.True(expr).</summary>
    /// <remarks>See <see href="https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit2004.md"/>.</remarks>
    [DiagnosticRule]
    public static class NUnit2004
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(NUnit2004);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = NUnitCategory.Assertion;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit2004.md";
    }

    /// <summary>Consider using Assert.That(actual, Is.EqualTo(expected)) instead of ClassicAssert.AreEqual(expected, actual).</summary>
    /// <remarks>See <see href="https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit2005.md"/>.</remarks>
    [DiagnosticRule]
    public static class NUnit2005
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(NUnit2005);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = NUnitCategory.Assertion;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit2005.md";
    }

    /// <summary>Consider using Assert.That(actual, Is.Not.EqualTo(expected)) instead of ClassicAssert.AreNotEqual(expected, actual).</summary>
    /// <remarks>See <see href="https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit2006.md"/>.</remarks>
    [DiagnosticRule]
    public static class NUnit2006
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(NUnit2006);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = NUnitCategory.Assertion;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit2006.md";
    }

    /// <summary>The actual value should not be a constant.</summary>
    /// <remarks>See <see href="https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit2007.md"/>.</remarks>
    [DiagnosticRule]
    public static class NUnit2007
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(NUnit2007);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = NUnitCategory.Assertion;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit2007.md";
    }

    /// <summary>Incorrect IgnoreCase usage.</summary>
    /// <remarks>See <see href="https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit2008.md"/>.</remarks>
    [DiagnosticRule]
    public static class NUnit2008
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(NUnit2008);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = NUnitCategory.Assertion;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit2008.md";
    }

    /// <summary>The same value has been provided as both the actual and the expected argument.</summary>
    /// <remarks>See <see href="https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit2009.md"/>.</remarks>
    [DiagnosticRule]
    public static class NUnit2009
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(NUnit2009);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = NUnitCategory.Assertion;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit2009.md";
    }

    /// <summary>Use EqualConstraint for better assertion messages in case of failure.</summary>
    /// <remarks>See <see href="https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit2010.md"/>.</remarks>
    [DiagnosticRule]
    public static class NUnit2010
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(NUnit2010);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = NUnitCategory.Assertion;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit2010.md";
    }

    /// <summary>Use ContainsConstraint for better assertion messages in case of failure.</summary>
    /// <remarks>See <see href="https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit2011.md"/>.</remarks>
    [DiagnosticRule]
    public static class NUnit2011
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(NUnit2011);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = NUnitCategory.Assertion;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit2011.md";
    }

    /// <summary>Use StartsWithConstraint for better assertion messages in case of failure.</summary>
    /// <remarks>See <see href="https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit2012.md"/>.</remarks>
    [DiagnosticRule]
    public static class NUnit2012
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(NUnit2012);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = NUnitCategory.Assertion;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit2012.md";
    }

    /// <summary>Use EndsWithConstraint for better assertion messages in case of failure.</summary>
    /// <remarks>See <see href="https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit2013.md"/>.</remarks>
    [DiagnosticRule]
    public static class NUnit2013
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(NUnit2013);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = NUnitCategory.Assertion;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit2013.md";
    }

    /// <summary>Use SomeItemsConstraint for better assertion messages in case of failure.</summary>
    /// <remarks>See <see href="https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit2014.md"/>.</remarks>
    [DiagnosticRule]
    public static class NUnit2014
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(NUnit2014);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = NUnitCategory.Assertion;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit2014.md";
    }

    /// <summary>Consider using Assert.That(actual, Is.SameAs(expected)) instead of ClassicAssert.AreSame(expected, actual).</summary>
    /// <remarks>See <see href="https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit2015.md"/>.</remarks>
    [DiagnosticRule]
    public static class NUnit2015
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(NUnit2015);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = NUnitCategory.Assertion;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit2015.md";
    }

    /// <summary>Consider using Assert.That(expr, Is.Null) instead of ClassicAssert.Null(expr).</summary>
    /// <remarks>See <see href="https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit2016.md"/>.</remarks>
    [DiagnosticRule]
    public static class NUnit2016
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(NUnit2016);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = NUnitCategory.Assertion;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit2016.md";
    }

    /// <summary>Consider using Assert.That(expr, Is.Null) instead of ClassicAssert.IsNull(expr).</summary>
    /// <remarks>See <see href="https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit2017.md"/>.</remarks>
    [DiagnosticRule]
    public static class NUnit2017
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(NUnit2017);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = NUnitCategory.Assertion;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit2017.md";
    }

    /// <summary>Consider using Assert.That(expr, Is.Not.Null) instead of ClassicAssert.NotNull(expr).</summary>
    /// <remarks>See <see href="https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit2018.md"/>.</remarks>
    [DiagnosticRule]
    public static class NUnit2018
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(NUnit2018);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = NUnitCategory.Assertion;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit2018.md";
    }

    /// <summary>Consider using Assert.That(expr, Is.Not.Null) instead of ClassicAssert.IsNotNull(expr).</summary>
    /// <remarks>See <see href="https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit2019.md"/>.</remarks>
    [DiagnosticRule]
    public static class NUnit2019
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(NUnit2019);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = NUnitCategory.Assertion;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit2019.md";
    }

    /// <summary>Incompatible types for SameAs constraint.</summary>
    /// <remarks>See <see href="https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit2020.md"/>.</remarks>
    [DiagnosticRule]
    public static class NUnit2020
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(NUnit2020);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = NUnitCategory.Assertion;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit2020.md";
    }

    /// <summary>Incompatible types for EqualTo constraint.</summary>
    /// <remarks>See <see href="https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit2021.md"/>.</remarks>
    [DiagnosticRule]
    public static class NUnit2021
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(NUnit2021);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = NUnitCategory.Assertion;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit2021.md";
    }

    /// <summary>Missing property required for constraint.</summary>
    /// <remarks>See <see href="https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit2022.md"/>.</remarks>
    [DiagnosticRule]
    public static class NUnit2022
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(NUnit2022);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = NUnitCategory.Assertion;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit2022.md";
    }

    /// <summary>Invalid NullConstraint usage.</summary>
    /// <remarks>See <see href="https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit2023.md"/>.</remarks>
    [DiagnosticRule]
    public static class NUnit2023
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(NUnit2023);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = NUnitCategory.Assertion;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit2023.md";
    }

    /// <summary>Wrong actual type used with String Constraint.</summary>
    /// <remarks>See <see href="https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit2024.md"/>.</remarks>
    [DiagnosticRule]
    public static class NUnit2024
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(NUnit2024);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = NUnitCategory.Assertion;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit2024.md";
    }

    /// <summary>Wrong actual type used with ContainsConstraint.</summary>
    /// <remarks>See <see href="https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit2025.md"/>.</remarks>
    [DiagnosticRule]
    public static class NUnit2025
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(NUnit2025);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = NUnitCategory.Assertion;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit2025.md";
    }

    /// <summary>Wrong actual type used with the SomeItemsConstraint with EqualConstraint.</summary>
    /// <remarks>See <see href="https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit2026.md"/>.</remarks>
    [DiagnosticRule]
    public static class NUnit2026
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(NUnit2026);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = NUnitCategory.Assertion;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit2026.md";
    }

    /// <summary>Consider using Assert.That(actual, Is.GreaterThan(expected)) instead of ClassicAssert.Greater(actual, expected).</summary>
    /// <remarks>See <see href="https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit2027.md"/>.</remarks>
    [DiagnosticRule]
    public static class NUnit2027
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(NUnit2027);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = NUnitCategory.Assertion;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit2027.md";
    }

    /// <summary>Consider using Assert.That(actual, Is.GreaterThanOrEqualTo(expected)) instead of ClassicAssert.GreaterOrEqual(actual, expected).</summary>
    /// <remarks>See <see href="https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit2028.md"/>.</remarks>
    [DiagnosticRule]
    public static class NUnit2028
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(NUnit2028);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = NUnitCategory.Assertion;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit2028.md";
    }

    /// <summary>Consider using Assert.That(actual, Is.LessThan(expected)) instead of ClassicAssert.Less(actual, expected).</summary>
    /// <remarks>See <see href="https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit2029.md"/>.</remarks>
    [DiagnosticRule]
    public static class NUnit2029
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(NUnit2029);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = NUnitCategory.Assertion;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit2029.md";
    }

    /// <summary>Consider using Assert.That(actual, Is.LessThanOrEqualTo(expected)) instead of ClassicAssert.LessOrEqual(actual, expected).</summary>
    /// <remarks>See <see href="https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit2030.md"/>.</remarks>
    [DiagnosticRule]
    public static class NUnit2030
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(NUnit2030);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = NUnitCategory.Assertion;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit2030.md";
    }

    /// <summary>Consider using Assert.That(actual, Is.Not.SameAs(expected)) instead of ClassicAssert.AreNotSame(expected, actual).</summary>
    /// <remarks>See <see href="https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit2031.md"/>.</remarks>
    [DiagnosticRule]
    public static class NUnit2031
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(NUnit2031);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = NUnitCategory.Assertion;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit2031.md";
    }

    /// <summary>Consider using Assert.That(expr, Is.Zero) instead of ClassicAssert.Zero(expr).</summary>
    /// <remarks>See <see href="https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit2032.md"/>.</remarks>
    [DiagnosticRule]
    public static class NUnit2032
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(NUnit2032);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = NUnitCategory.Assertion;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit2032.md";
    }

    /// <summary>Consider using Assert.That(expr, Is.Not.Zero) instead of ClassicAssert.NotZero(expr).</summary>
    /// <remarks>See <see href="https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit2033.md"/>.</remarks>
    [DiagnosticRule]
    public static class NUnit2033
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(NUnit2033);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = NUnitCategory.Assertion;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit2033.md";
    }

    /// <summary>Consider using Assert.That(expr, Is.NaN) instead of ClassicAssert.IsNaN(expr).</summary>
    /// <remarks>See <see href="https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit2034.md"/>.</remarks>
    [DiagnosticRule]
    public static class NUnit2034
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(NUnit2034);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = NUnitCategory.Assertion;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit2034.md";
    }

    /// <summary>Consider using Assert.That(collection, Is.Empty) instead of ClassicAssert.IsEmpty(collection).</summary>
    /// <remarks>See <see href="https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit2035.md"/>.</remarks>
    [DiagnosticRule]
    public static class NUnit2035
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(NUnit2035);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = NUnitCategory.Assertion;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit2035.md";
    }

    /// <summary>Consider using Assert.That(collection, Is.Not.Empty) instead of ClassicAssert.IsNotEmpty(collection).</summary>
    /// <remarks>See <see href="https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit2036.md"/>.</remarks>
    [DiagnosticRule]
    public static class NUnit2036
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(NUnit2036);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = NUnitCategory.Assertion;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit2036.md";
    }

    /// <summary>Consider using Assert.That(collection, Does.Contain(instance)) instead of ClassicAssert.Contains(instance, collection).</summary>
    /// <remarks>See <see href="https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit2037.md"/>.</remarks>
    [DiagnosticRule]
    public static class NUnit2037
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(NUnit2037);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = NUnitCategory.Assertion;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit2037.md";
    }

    /// <summary>Consider using Assert.That(actual, Is.InstanceOf(expected)) instead of ClassicAssert.IsInstanceOf(expected, actual).</summary>
    /// <remarks>See <see href="https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit2038.md"/>.</remarks>
    [DiagnosticRule]
    public static class NUnit2038
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(NUnit2038);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = NUnitCategory.Assertion;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit2038.md";
    }

    /// <summary>Consider using Assert.That(actual, Is.Not.InstanceOf(expected)) instead of ClassicAssert.IsNotInstanceOf(expected, actual).</summary>
    /// <remarks>See <see href="https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit2039.md"/>.</remarks>
    [DiagnosticRule]
    public static class NUnit2039
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(NUnit2039);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = NUnitCategory.Assertion;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit2039.md";
    }

    /// <summary>Non-reference types for SameAs constraint.</summary>
    /// <remarks>See <see href="https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit2040.md"/>.</remarks>
    [DiagnosticRule]
    public static class NUnit2040
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(NUnit2040);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = NUnitCategory.Assertion;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit2040.md";
    }

    /// <summary>Incompatible types for comparison constraint.</summary>
    /// <remarks>See <see href="https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit2041.md"/>.</remarks>
    [DiagnosticRule]
    public static class NUnit2041
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(NUnit2041);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = NUnitCategory.Assertion;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit2041.md";
    }

    /// <summary>Comparison constraint on object.</summary>
    /// <remarks>See <see href="https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit2042.md"/>.</remarks>
    [DiagnosticRule]
    public static class NUnit2042
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(NUnit2042);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = NUnitCategory.Assertion;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit2042.md";
    }

    /// <summary>Use ComparisonConstraint for better assertion messages in case of failure.</summary>
    /// <remarks>See <see href="https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit2043.md"/>.</remarks>
    [DiagnosticRule]
    public static class NUnit2043
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(NUnit2043);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = NUnitCategory.Assertion;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit2043.md";
    }

    /// <summary>Non-delegate actual parameter.</summary>
    /// <remarks>See <see href="https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit2044.md"/>.</remarks>
    [DiagnosticRule]
    public static class NUnit2044
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(NUnit2044);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = NUnitCategory.Assertion;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit2044.md";
    }

    /// <summary>Use Assert.EnterMultipleScope or Assert.Multiple.</summary>
    /// <remarks>See <see href="https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit2045.md"/>.</remarks>
    [DiagnosticRule]
    public static class NUnit2045
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(NUnit2045);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = NUnitCategory.Assertion;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit2045.md";
    }

    /// <summary>Use CollectionConstraint for better assertion messages in case of failure.</summary>
    /// <remarks>See <see href="https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit2046.md"/>.</remarks>
    [DiagnosticRule]
    public static class NUnit2046
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(NUnit2046);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = NUnitCategory.Assertion;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit2046.md";
    }

    /// <summary>Incompatible types for Within constraint.</summary>
    /// <remarks>See <see href="https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit2047.md"/>.</remarks>
    [DiagnosticRule]
    public static class NUnit2047
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(NUnit2047);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = NUnitCategory.Assertion;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit2047.md";
    }

    /// <summary>Consider using Assert.That(...) instead of StringAssert(...).</summary>
    /// <remarks>See <see href="https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit2048.md"/>.</remarks>
    [DiagnosticRule]
    public static class NUnit2048
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(NUnit2048);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = NUnitCategory.Assertion;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit2048.md";
    }

    /// <summary>Consider using Assert.That(...) instead of CollectionAssert(...).</summary>
    /// <remarks>See <see href="https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit2049.md"/>.</remarks>
    [DiagnosticRule]
    public static class NUnit2049
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(NUnit2049);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = NUnitCategory.Assertion;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit2049.md";
    }

    /// <summary>NUnit 4 no longer supports string.Format specification.</summary>
    /// <remarks>See <see href="https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit2050.md"/>.</remarks>
    [DiagnosticRule]
    public static class NUnit2050
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(NUnit2050);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = NUnitCategory.Assertion;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit2050.md";
    }

    /// <summary>Consider using Assert.That(expr, Is.Positive) instead of ClassicAssert.Positive(expr).</summary>
    /// <remarks>See <see href="https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit2051.md"/>.</remarks>
    [DiagnosticRule]
    public static class NUnit2051
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(NUnit2051);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = NUnitCategory.Assertion;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit2051.md";
    }

    /// <summary>Consider using Assert.That(expr, Is.Negative) instead of ClassicAssert.Negative(expr).</summary>
    /// <remarks>See <see href="https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit2052.md"/>.</remarks>
    [DiagnosticRule]
    public static class NUnit2052
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(NUnit2052);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = NUnitCategory.Assertion;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit2052.md";
    }

    /// <summary>Consider using Assert.That(actual, Is.AssignableFrom(expected)) instead of ClassicAssert.IsAssignableFrom(expected, actual).</summary>
    /// <remarks>See <see href="https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit2053.md"/>.</remarks>
    [DiagnosticRule]
    public static class NUnit2053
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(NUnit2053);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = NUnitCategory.Assertion;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit2053.md";
    }

    /// <summary>Consider using Assert.That(actual, Is.Not.AssignableFrom(expected)) instead of ClassicAssert.IsNotAssignableFrom(expected, actual).</summary>
    /// <remarks>See <see href="https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit2054.md"/>.</remarks>
    [DiagnosticRule]
    public static class NUnit2054
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(NUnit2054);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = NUnitCategory.Assertion;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit2054.md";
    }

    /// <summary>Consider using Is.InstanceOf&lt;T&gt; constraint instead of an 'is T' expression.</summary>
    /// <remarks>See <see href="https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit2055.md"/>.</remarks>
    [DiagnosticRule]
    public static class NUnit2055
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(NUnit2055);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = NUnitCategory.Assertion;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit2055.md";
    }

    /// <summary>Consider using Assert.EnterMultipleScope statement instead of Assert.Multiple/Assert.MultipleAsync.</summary>
    /// <remarks>See <see href="https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit2056.md"/>.</remarks>
    [DiagnosticRule]
    public static class NUnit2056
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(NUnit2056);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = NUnitCategory.Assertion;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit2056.md";
    }

    /// <summary>Remove unnecessary lambda expression.</summary>
    /// <remarks>See <see href="https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit2057.md"/>.</remarks>
    [DiagnosticRule]
    public static class NUnit2057
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(NUnit2057);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = NUnitCategory.Assertion;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit2057.md";
    }

    /// <summary>The constraint is misused.</summary>
    /// <remarks>See <see href="https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit2058.md"/>.</remarks>
    [DiagnosticRule]
    public static class NUnit2058
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(NUnit2058);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = NUnitCategory.Assertion;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit2058.md";
    }

    /// <summary>Task result of method should be used.</summary>
    /// <remarks>See <see href="https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit2059.md"/>.</remarks>
    [DiagnosticRule]
    public static class NUnit2059
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(NUnit2059);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = NUnitCategory.Assertion;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit2059.md";
    }

    /// <summary>Simplify the Values attribute.</summary>
    /// <remarks>See <see href="https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit4001.md"/>.</remarks>
    [DiagnosticRule]
    public static class NUnit4001
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(NUnit4001);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = NUnitCategory.Style;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit4001.md";
    }

    /// <summary>Use Specific constraint.</summary>
    /// <remarks>See <see href="https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit4002.md"/>.</remarks>
    [DiagnosticRule]
    public static class NUnit4002
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(NUnit4002);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = NUnitCategory.Style;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit4002.md";
    }
}
