// <auto-generated>
//     Generated by eng/CatalogGen from the DiagnosticDescriptor instances declared by
//     Microsoft.CodeAnalysis.Analyzers 5.6.0 (language: cs).
//     Do not edit by hand: rerun the generator.
//
//     Only Id, Category, Title and HelpLinkUri are emitted, and only when the
//     descriptor actually supplies them. A rule's title is reproduced verbatim as its
//     documentation comment: it is the one sentence that says what the rule is about,
//     and it is Microsoft.CodeAnalysis.Analyzers's own wording. Rule descriptions and message
//     formats are the vendor's documentation and are not redistributed here.
// </auto-generated>

using DiagnosticCatalog;

[assembly: CatalogSource(
    source:        "Microsoft.CodeAnalysis.Analyzers",
    sourceVersion: "5.6.0",
    generatedOn:   "2026-08-05")]

namespace DiagnosticCatalog.Roslyn;

/// <summary>
/// The diagnostic categories used by Microsoft.CodeAnalysis.Analyzers, declared once each.
/// </summary>
/// <remarks>
/// INTERNAL by design. A category is reachable only through the rule that carries it:
/// write <c>SomeRule.Sxxxx.Category</c>, never the category constant directly. The two
/// spellings fold to the same string today and stop agreeing the day the vendor moves the
/// rule to another category -- the rule member follows, a category named on its own does
/// not, and the suppression is left asserting a category the rule no longer carries.
/// Nothing reports that: Roslyn ignores the category when it matches a suppression, so the
/// mistake has no symptom at all. Keeping this class out of the public surface makes that
/// decoupling unwritable rather than merely discouraged.
/// The public <c>Category</c> constant on each rule is initialised from here and folds to
/// the literal at compile time, so a consumer loses nothing.
/// </remarks>
[DiagnosticCategory]
internal static class RoslynCategory
{
    /// <summary>The <c>Correctness</c> category.</summary>
    public const string Correctness = "Correctness";

    /// <summary>The <c>Library</c> category.</summary>
    public const string Library = "Library";

    /// <summary>The <c>MicrosoftCodeAnalysisCompatibility</c> category.</summary>
    public const string MicrosoftCodeAnalysisCompatibility = "MicrosoftCodeAnalysisCompatibility";

    /// <summary>The <c>MicrosoftCodeAnalysisCorrectness</c> category.</summary>
    public const string MicrosoftCodeAnalysisCorrectness = "MicrosoftCodeAnalysisCorrectness";

    /// <summary>The <c>MicrosoftCodeAnalysisDesign</c> category.</summary>
    public const string MicrosoftCodeAnalysisDesign = "MicrosoftCodeAnalysisDesign";

    /// <summary>The <c>MicrosoftCodeAnalysisDocumentation</c> category.</summary>
    public const string MicrosoftCodeAnalysisDocumentation = "MicrosoftCodeAnalysisDocumentation";

    /// <summary>The <c>MicrosoftCodeAnalysisLocalization</c> category.</summary>
    public const string MicrosoftCodeAnalysisLocalization = "MicrosoftCodeAnalysisLocalization";

    /// <summary>The <c>MicrosoftCodeAnalysisPerformance</c> category.</summary>
    public const string MicrosoftCodeAnalysisPerformance = "MicrosoftCodeAnalysisPerformance";

    /// <summary>The <c>MicrosoftCodeAnalysisReleaseTracking</c> category.</summary>
    public const string MicrosoftCodeAnalysisReleaseTracking = "MicrosoftCodeAnalysisReleaseTracking";
}

/// <summary>
/// The Microsoft.CodeAnalysis.Analyzers diagnostic rules, as declared by that package's analyzers.
/// </summary>
public static class RoslynRule
{
    /// <summary>Missing diagnostic analyzer attribute.</summary>
    [DiagnosticRule]
    public static class RS1001
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(RS1001);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = RoslynCategory.MicrosoftCodeAnalysisCorrectness;
    }

    /// <summary>Missing kind argument when registering an analyzer action.</summary>
    [DiagnosticRule]
    public static class RS1002
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(RS1002);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = RoslynCategory.MicrosoftCodeAnalysisCorrectness;
    }

    /// <summary>Unsupported SymbolKind argument when registering a symbol analyzer action.</summary>
    [DiagnosticRule]
    public static class RS1003
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(RS1003);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = RoslynCategory.MicrosoftCodeAnalysisCorrectness;
    }

    /// <summary>Recommend adding language support to diagnostic analyzer.</summary>
    [DiagnosticRule]
    public static class RS1004
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(RS1004);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = RoslynCategory.MicrosoftCodeAnalysisCorrectness;
    }

    /// <summary>ReportDiagnostic invoked with an unsupported DiagnosticDescriptor.</summary>
    [DiagnosticRule]
    public static class RS1005
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(RS1005);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = RoslynCategory.MicrosoftCodeAnalysisCorrectness;
    }

    /// <summary>Invalid type argument for DiagnosticAnalyzer's Register method.</summary>
    [DiagnosticRule]
    public static class RS1006
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(RS1006);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = RoslynCategory.MicrosoftCodeAnalysisCorrectness;
    }

    /// <summary>Provide localizable arguments to diagnostic descriptor constructor.</summary>
    [DiagnosticRule]
    public static class RS1007
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(RS1007);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = RoslynCategory.MicrosoftCodeAnalysisLocalization;
    }

    /// <summary>Avoid storing per-compilation data into the fields of a diagnostic analyzer.</summary>
    [DiagnosticRule]
    public static class RS1008
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(RS1008);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = RoslynCategory.MicrosoftCodeAnalysisPerformance;
    }

    /// <summary>Only internal implementations of this interface are allowed.</summary>
    [DiagnosticRule]
    public static class RS1009
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(RS1009);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = RoslynCategory.MicrosoftCodeAnalysisCompatibility;
    }

    /// <summary>Create code actions should have a unique EquivalenceKey for FixAll occurrences support.</summary>
    [DiagnosticRule]
    public static class RS1010
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(RS1010);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = RoslynCategory.Correctness;
    }

    /// <summary>Use code actions that have a unique EquivalenceKey for FixAll occurrences support.</summary>
    [DiagnosticRule]
    public static class RS1011
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(RS1011);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = RoslynCategory.Correctness;
    }

    /// <summary>Start action has no registered actions.</summary>
    [DiagnosticRule]
    public static class RS1012
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(RS1012);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = RoslynCategory.MicrosoftCodeAnalysisPerformance;
    }

    /// <summary>Start action has no registered non-end actions.</summary>
    [DiagnosticRule]
    public static class RS1013
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(RS1013);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = RoslynCategory.MicrosoftCodeAnalysisPerformance;
    }

    /// <summary>Do not ignore values returned by methods on immutable objects.</summary>
    [DiagnosticRule]
    public static class RS1014
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(RS1014);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = RoslynCategory.MicrosoftCodeAnalysisCorrectness;
    }

    /// <summary>Provide non-null 'helpLinkUri' value to diagnostic descriptor constructor.</summary>
    [DiagnosticRule]
    public static class RS1015
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(RS1015);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = RoslynCategory.MicrosoftCodeAnalysisDocumentation;
    }

    /// <summary>Code fix providers should provide FixAll support.</summary>
    [DiagnosticRule]
    public static class RS1016
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(RS1016);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = RoslynCategory.Correctness;
    }

    /// <summary>DiagnosticId for analyzers must be a non-null constant.</summary>
    [DiagnosticRule]
    public static class RS1017
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(RS1017);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = RoslynCategory.MicrosoftCodeAnalysisDesign;
    }

    /// <summary>DiagnosticId for analyzers must be in specified format.</summary>
    [DiagnosticRule]
    public static class RS1018
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(RS1018);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = RoslynCategory.MicrosoftCodeAnalysisDesign;
    }

    /// <summary>DiagnosticId must be unique across analyzers.</summary>
    [DiagnosticRule]
    public static class RS1019
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(RS1019);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = RoslynCategory.MicrosoftCodeAnalysisDesign;
    }

    /// <summary>Category for analyzers must be from the specified values.</summary>
    [DiagnosticRule]
    public static class RS1020
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(RS1020);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = RoslynCategory.MicrosoftCodeAnalysisDesign;
    }

    /// <summary>Invalid entry in analyzer category and diagnostic ID range specification file.</summary>
    [DiagnosticRule]
    public static class RS1021
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(RS1021);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = RoslynCategory.MicrosoftCodeAnalysisDesign;
    }

    /// <summary>Do not use types from Workspaces assembly in an analyzer.</summary>
    /// <remarks>See <see href="https://github.com/dotnet/roslyn/blob/main/docs/roslyn-analyzers/rules/RS1022.md"/>.</remarks>
    [DiagnosticRule]
    public static class RS1022
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(RS1022);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = RoslynCategory.MicrosoftCodeAnalysisCorrectness;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/dotnet/roslyn/blob/main/docs/roslyn-analyzers/rules/RS1022.md";
    }

    /// <summary>Upgrade MSBuildWorkspace.</summary>
    /// <remarks>See <see href="https://go.microsoft.com/fwlink/?linkid=874285"/>.</remarks>
    [DiagnosticRule]
    public static class RS1023
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(RS1023);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = RoslynCategory.Library;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://go.microsoft.com/fwlink/?linkid=874285";
    }

    /// <summary>Symbols should be compared for equality.</summary>
    [DiagnosticRule]
    public static class RS1024
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(RS1024);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = RoslynCategory.MicrosoftCodeAnalysisCorrectness;
    }

    /// <summary>Configure generated code analysis.</summary>
    [DiagnosticRule]
    public static class RS1025
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(RS1025);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = RoslynCategory.MicrosoftCodeAnalysisCorrectness;
    }

    /// <summary>Enable concurrent execution.</summary>
    [DiagnosticRule]
    public static class RS1026
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(RS1026);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = RoslynCategory.MicrosoftCodeAnalysisCorrectness;
    }

    /// <summary>Types marked with DiagnosticAnalyzerAttribute(s) should inherit from DiagnosticAnalyzer.</summary>
    [DiagnosticRule]
    public static class RS1027
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(RS1027);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = RoslynCategory.MicrosoftCodeAnalysisCorrectness;
    }

    /// <summary>Provide non-null 'customTags' value to diagnostic descriptor constructor.</summary>
    [DiagnosticRule]
    public static class RS1028
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(RS1028);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = RoslynCategory.MicrosoftCodeAnalysisDocumentation;
    }

    /// <summary>Do not use reserved diagnostic IDs.</summary>
    [DiagnosticRule]
    public static class RS1029
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(RS1029);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = RoslynCategory.MicrosoftCodeAnalysisDesign;
    }

    /// <summary>Do not invoke Compilation.GetSemanticModel() method within a diagnostic analyzer.</summary>
    [DiagnosticRule]
    public static class RS1030
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(RS1030);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = RoslynCategory.MicrosoftCodeAnalysisCorrectness;
    }

    /// <summary>Define diagnostic title correctly.</summary>
    [DiagnosticRule]
    public static class RS1031
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(RS1031);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = RoslynCategory.MicrosoftCodeAnalysisDesign;
    }

    /// <summary>Define diagnostic message correctly.</summary>
    [DiagnosticRule]
    public static class RS1032
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(RS1032);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = RoslynCategory.MicrosoftCodeAnalysisDesign;
    }

    /// <summary>Define diagnostic description correctly.</summary>
    [DiagnosticRule]
    public static class RS1033
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(RS1033);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = RoslynCategory.MicrosoftCodeAnalysisDesign;
    }

    /// <summary>Prefer 'IsKind' for checking syntax kinds.</summary>
    [DiagnosticRule]
    public static class RS1034
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(RS1034);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = RoslynCategory.MicrosoftCodeAnalysisPerformance;
    }

    /// <summary>Do not use APIs banned for analyzers.</summary>
    [DiagnosticRule]
    public static class RS1035
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(RS1035);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = RoslynCategory.MicrosoftCodeAnalysisCorrectness;
    }

    /// <summary>Specify analyzer banned API enforcement setting.</summary>
    [DiagnosticRule]
    public static class RS1036
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(RS1036);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = RoslynCategory.MicrosoftCodeAnalysisCorrectness;
    }

    /// <summary>Add "CompilationEnd" custom tag to compilation end diagnostic descriptor.</summary>
    [DiagnosticRule]
    public static class RS1037
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(RS1037);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = RoslynCategory.MicrosoftCodeAnalysisDesign;
    }

    /// <summary>Compiler extensions should be implemented in assemblies with compiler-provided references.</summary>
    /// <remarks>See <see href="https://github.com/dotnet/roslyn/blob/main/docs/roslyn-analyzers/rules/RS1038.md"/>.</remarks>
    [DiagnosticRule]
    public static class RS1038
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(RS1038);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = RoslynCategory.MicrosoftCodeAnalysisCorrectness;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/dotnet/roslyn/blob/main/docs/roslyn-analyzers/rules/RS1038.md";
    }

    /// <summary>This call to 'SemanticModel.GetDeclaredSymbol()' will always return 'null'.</summary>
    [DiagnosticRule]
    public static class RS1039
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(RS1039);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = RoslynCategory.MicrosoftCodeAnalysisCorrectness;
    }

    /// <summary>This call to 'SemanticModel.GetDeclaredSymbol()' will always return 'null'.</summary>
    [DiagnosticRule]
    public static class RS1040
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(RS1040);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = RoslynCategory.MicrosoftCodeAnalysisCorrectness;
    }

    /// <summary>Compiler extensions should be implemented in assemblies targeting netstandard2.0.</summary>
    /// <remarks>See <see href="https://github.com/dotnet/roslyn/blob/main/docs/roslyn-analyzers/rules/RS1041.md"/>.</remarks>
    [DiagnosticRule]
    public static class RS1041
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(RS1041);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = RoslynCategory.MicrosoftCodeAnalysisCorrectness;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/dotnet/roslyn/blob/main/docs/roslyn-analyzers/rules/RS1041.md";
    }

    /// <summary>Implementations of this interface are not allowed.</summary>
    [DiagnosticRule]
    public static class RS1042
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(RS1042);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = RoslynCategory.MicrosoftCodeAnalysisCompatibility;
    }

    /// <summary>Do not use file types for implementing analyzers, generators, and code fixers.</summary>
    [DiagnosticRule]
    public static class RS1043
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(RS1043);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = RoslynCategory.MicrosoftCodeAnalysisCorrectness;
    }

    /// <summary>Add analyzer diagnostic IDs to analyzer release.</summary>
    /// <remarks>See <see href="https://github.com/dotnet/roslyn/blob/main/src/RoslynAnalyzers/Microsoft.CodeAnalysis.Analyzers/ReleaseTrackingAnalyzers.Help.md"/>.</remarks>
    [DiagnosticRule]
    public static class RS2000
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(RS2000);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = RoslynCategory.MicrosoftCodeAnalysisReleaseTracking;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/dotnet/roslyn/blob/main/src/RoslynAnalyzers/Microsoft.CodeAnalysis.Analyzers/ReleaseTrackingAnalyzers.Help.md";
    }

    /// <summary>Ensure up-to-date entry for analyzer diagnostic IDs are added to analyzer release.</summary>
    /// <remarks>See <see href="https://github.com/dotnet/roslyn/blob/main/src/RoslynAnalyzers/Microsoft.CodeAnalysis.Analyzers/ReleaseTrackingAnalyzers.Help.md"/>.</remarks>
    [DiagnosticRule]
    public static class RS2001
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(RS2001);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = RoslynCategory.MicrosoftCodeAnalysisReleaseTracking;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/dotnet/roslyn/blob/main/src/RoslynAnalyzers/Microsoft.CodeAnalysis.Analyzers/ReleaseTrackingAnalyzers.Help.md";
    }

    /// <summary>Do not add removed analyzer diagnostic IDs to unshipped analyzer release.</summary>
    /// <remarks>See <see href="https://github.com/dotnet/roslyn/blob/main/src/RoslynAnalyzers/Microsoft.CodeAnalysis.Analyzers/ReleaseTrackingAnalyzers.Help.md"/>.</remarks>
    [DiagnosticRule]
    public static class RS2002
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(RS2002);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = RoslynCategory.MicrosoftCodeAnalysisReleaseTracking;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/dotnet/roslyn/blob/main/src/RoslynAnalyzers/Microsoft.CodeAnalysis.Analyzers/ReleaseTrackingAnalyzers.Help.md";
    }

    /// <summary>Shipped diagnostic IDs that are no longer reported should have an entry in the 'Removed Rules' table in unshipped file.</summary>
    /// <remarks>See <see href="https://github.com/dotnet/roslyn/blob/main/src/RoslynAnalyzers/Microsoft.CodeAnalysis.Analyzers/ReleaseTrackingAnalyzers.Help.md"/>.</remarks>
    [DiagnosticRule]
    public static class RS2003
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(RS2003);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = RoslynCategory.MicrosoftCodeAnalysisReleaseTracking;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/dotnet/roslyn/blob/main/src/RoslynAnalyzers/Microsoft.CodeAnalysis.Analyzers/ReleaseTrackingAnalyzers.Help.md";
    }

    /// <summary>Diagnostic IDs marked as removed in analyzer release file should not be reported by analyzers.</summary>
    /// <remarks>See <see href="https://github.com/dotnet/roslyn/blob/main/src/RoslynAnalyzers/Microsoft.CodeAnalysis.Analyzers/ReleaseTrackingAnalyzers.Help.md"/>.</remarks>
    [DiagnosticRule]
    public static class RS2004
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(RS2004);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = RoslynCategory.MicrosoftCodeAnalysisReleaseTracking;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/dotnet/roslyn/blob/main/src/RoslynAnalyzers/Microsoft.CodeAnalysis.Analyzers/ReleaseTrackingAnalyzers.Help.md";
    }

    /// <summary>Remove duplicate entries for diagnostic ID in the same analyzer release.</summary>
    /// <remarks>See <see href="https://github.com/dotnet/roslyn/blob/main/src/RoslynAnalyzers/Microsoft.CodeAnalysis.Analyzers/ReleaseTrackingAnalyzers.Help.md"/>.</remarks>
    [DiagnosticRule]
    public static class RS2005
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(RS2005);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = RoslynCategory.MicrosoftCodeAnalysisReleaseTracking;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/dotnet/roslyn/blob/main/src/RoslynAnalyzers/Microsoft.CodeAnalysis.Analyzers/ReleaseTrackingAnalyzers.Help.md";
    }

    /// <summary>Remove duplicate entries for diagnostic ID between analyzer releases.</summary>
    /// <remarks>See <see href="https://github.com/dotnet/roslyn/blob/main/src/RoslynAnalyzers/Microsoft.CodeAnalysis.Analyzers/ReleaseTrackingAnalyzers.Help.md"/>.</remarks>
    [DiagnosticRule]
    public static class RS2006
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(RS2006);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = RoslynCategory.MicrosoftCodeAnalysisReleaseTracking;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/dotnet/roslyn/blob/main/src/RoslynAnalyzers/Microsoft.CodeAnalysis.Analyzers/ReleaseTrackingAnalyzers.Help.md";
    }

    /// <summary>Invalid entry in analyzer release file.</summary>
    /// <remarks>See <see href="https://github.com/dotnet/roslyn/blob/main/src/RoslynAnalyzers/Microsoft.CodeAnalysis.Analyzers/ReleaseTrackingAnalyzers.Help.md"/>.</remarks>
    [DiagnosticRule]
    public static class RS2007
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(RS2007);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = RoslynCategory.MicrosoftCodeAnalysisReleaseTracking;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/dotnet/roslyn/blob/main/src/RoslynAnalyzers/Microsoft.CodeAnalysis.Analyzers/ReleaseTrackingAnalyzers.Help.md";
    }

    /// <summary>Enable analyzer release tracking.</summary>
    /// <remarks>See <see href="https://github.com/dotnet/roslyn/blob/main/src/RoslynAnalyzers/Microsoft.CodeAnalysis.Analyzers/ReleaseTrackingAnalyzers.Help.md"/>.</remarks>
    [DiagnosticRule]
    public static class RS2008
    {
        /// <summary>The canonical identifier of this diagnostic.</summary>
        public const string Id = nameof(RS2008);

        /// <summary>The category declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string Category = RoslynCategory.MicrosoftCodeAnalysisReleaseTracking;

        /// <summary>The help link declared by the analyzer's DiagnosticDescriptor.</summary>
        public const string HelpLinkUri = "https://github.com/dotnet/roslyn/blob/main/src/RoslynAnalyzers/Microsoft.CodeAnalysis.Analyzers/ReleaseTrackingAnalyzers.Help.md";
    }
}
